### ISSUE TITLE
cmake can't find libuv files

### ISSUE THREAD

**Issue by jewel-snake** [oxen-io/lokinet#1402]
Got an error while compiling lokinet v8.0.0
`Make Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBUV_LIBRARY (ADVANCED)
    linked by target "lokinet-platform" in directory /home/kun/Downloads/loki-network/llarp`
despite that I have libuv installed on my PC. Got this issue on three different machines and two different OS(Arch and Void).

**Comment by majestrate** [comment]
On Sat, 2020-10-10 at 09:22 -0700, jewel-snake wrote:
> Got an error while compiling lokinet v8.0.0
> Make Error: The following variables are used in this project, but
> they are set to NOTFOUND. Please set them or make sure they are set
> and tested correctly in the CMake files: LIBUV_LIBRARY (ADVANCED)
> linked by target "lokinet-platform" in directory
> /home/kun/Downloads/loki-network/llarp
> despite that I have libuv installed on my PC. Got this issue on three
> different machines and two different OS(Arch and Void).
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

on debian the package is libuv1-dev, you may also need pkgconfig.

**Comment by jewel-snake** [comment]
Reffering to [this](https://bbs.archlinux.org/viewtopic.php?id=41231) arch linux forum thread I assume that  I have that package installed.

**Comment by majestrate** [comment]
On Sat, 2020-10-10 at 11:22 -0700, jewel-snake wrote:
> Reffering to this arch linux forum thread I assume that I have that
> package installed.
> 
> —
> 
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

what version of libuv do you have install?
do you have pkgconfig as well?

**Comment by jewel-snake** [comment]
>libuv
1.40.0-1
>pkgconfig
1.7.3-1

**Comment by jagerman** [comment]
What do you get if you run:
```
pkg-config --libs --cflags libuv
```
?

**Comment by majestrate** [comment]
On Sat, 2020-10-10 at 11:45 -0700, jewel-snake wrote:
> > libuv
> > 1.40.0-1
> > pkgconfig
> > 1.7.3-1
> > 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

i have just reproduced this in a VM

**Comment by majestrate** [comment]
a work around would be adding `-DDOWNLOAD_UV=FORCE` as a build option for now

**Comment by majestrate** [comment]
yeah the libuv cmake detection is screwed up it seems.

**Comment by jewel-snake** [comment]
> pkg-config --libs --cflags libuv

-luv -ldl

**Comment by jewel-snake** [comment]
with `-DDOWNLOAD_UV=FORCE` cmake step passes normally, and installation went fine. 
But I still can't get it work, starting lokinet crashes arguing
`Error trying to init and parse config from file: unrecognized option [network]:profiles`
and starting lokinet.service gives no result, but I think it is theme for another issue.

**Comment by majestrate** [comment]
this should be fixed by #1431
