### ISSUE TITLE
Specifying relatve lokinet.ini without `./` prefix fails

### ISSUE THREAD

**Issue by cathugger** [oxen-io/lokinet#1430]
**Describe the bug**
When starting lokinet as `lokinet lokinet.ini`, it fails with
```
[NFO] [lokinet](763) 2020-10-28 20:33:39.864 GMT [+0.001s] main.cpp:261 Using config file: "lokinet.ini"
[ERR] [lokinet](763) 2020-10-28 20:33:39.890 GMT [+0.027s] config/config.cpp:1054       Error trying to init and parse config from file: Specified [router]:data-dir "" d
oes not exist
[ERR] [lokinet](763) 2020-10-28 20:33:39.890 GMT [+0.027s] main.cpp:289 Fatal: caught exception while running: Config file parsing failed
main thread threw exception: Config file parsing failed
```
Starting as `lokinet ./lokinet.ini` works. If `data-dir "."` in config file gets specified, that works too, since it overrides option which causes failure.

**To Reproduce**
`lokinet lokinet.ini` (with data-dir commented out in config file).

**Screenshots Or Logs**
(specified above)

**Device and Operating system (please complete the following information):**
 - OS: aarch64 gentoo (but shouldn't matter)
-  Device: espressobin, doesn't matter
 - Lokinet Version number or Git commit hash: 0.8.1-rc1 but was problem in 0.8.0 too

**Comment by majestrate** [comment]
fixed by #1432
