### ISSUE TITLE
can't connect to lokinet-linux

### ISSUE THREAD

**Issue by rodseb** [oxen-io/lokinet#1458]
**Describe the bug**
do not connect

**To Reproduce**
I followed the explanation on github

**Screenshots Or Logs**
[loki.log](https://github.com/loki-project/loki-network/files/5505659/loki.log)

**Device and Operating system :**
 - OS: Linux Fedora 33 (Workstation Edition)
-  Device: PC
 - Lokinet Version number : lokinet-linux-amd64-20201003T023559Z-b67df3aaf (Releases 0.8.0)
PS : I have the same error with the version Releases 0.7.1

**Comment by majestrate** [comment]
looks like the seed node is not responding... cc @jagerman

**Comment by majestrate** [comment]
okay this should be resolved now, let me know.

**Comment by rodseb** [comment]
Hi @majestrate 
here are the logs

[loki.log](https://github.com/loki-project/loki-network/files/5506975/loki.log)

**Comment by majestrate** [comment]
yeah that path build issue is fixed in 0.8.1 but we have one outstanding bug we need to squash before releasing it.
