### ISSUE TITLE
Failed to connect to lokid

### ISSUE THREAD

**Issue by Naia-love** [oxen-io/lokinet#1489]
**Describe the bug**
Tried to install a lokinet rooter on a fresh user but systemctl complain that the soft crashed and try to restart it.
I deactivated my firewall to test so i don't think it's a problem with rejected connection (tho i would like to know the port to activate it back; it's 53 and 1090 right?)

**To Reproduce**
Try to install lokinet router with apt on Ubuntu

**Screenshots Or Logs**
```
MT [+0.066s] rpc/lokid_rpc_client.cpp:54        connecting to lokid via LMQ at ipc:///var/lib/loki/lokid.sock
MT [+0.066s] router_contact.cpp:545        Failed to open "/var/lib/lokinet/router/self.signed"
MT [+0.066s] router/router.cpp:551        Loaded 1 bootstrap routers
MT [+0.068s] router/router.cpp:621        router profiling enabled
MT [+0.068s] router/router.cpp:624        no profiles file at "/var/lib/lokinet/router/profiles.dat" skipping
MT [+0.068s] router/router.cpp:647        Initializing peerdb...
MT [+0.068s] peerstats/peer_db.cpp:30        Loading PeerDb from file /var/lib/lokinet/router/peerstats.sqlite
MT [+0.069s] peerstats/peer_db.cpp:41        Loading 0 PeerStats from table peerstats...
069s] util/logging/logger.cpp:143        Logger remains stdout
.123s] rpc/lokid_rpc_client.cpp:59        Failed to connect to lokid: connection attempt timed out
```

**Device and Operating system (please complete the following information):**
 - OS: Ubuntu 20.04
-  Device: Vultr server
 - Lokinet Version number or Git commit hash: lokinet-router 0.8.1-3~ubuntu2004 all

**Comment by majestrate** [comment]
if you are running a network fork with no service node staking set `enabled=false` in the `[lokid]` in `/var/lib/lokinet/lokinet.ini`. otherwise install the `loki-service-node` meta package which pulls in lokid.

**Comment by Naia-love** [comment]
I just followed what writed [here](https://docs.loki.network/Lokinet/Guides/LokinetRouter/) but yeah sorry installing the service-node make it work.
But now it's loki storage who seems to not work
it just print:
```
[2020-11-19 15:29:49.524] [critical] [operator()] Error retrieving SN privkey from lokid @ 127.0.0.1:22023: returned value is not hex. Error retrieving SN privkey from lokid @ 127.0.0.1:22023: returned value is not hex.  Is lokid running?  Retrying in 5s
```
tho lokid seems to work now as lokinetwork do ^^'

**Comment by majestrate** [comment]
i see, if the storage server doesn't work try making an issue there too: https://github.com/loki-project/loki-storage-server/issues

**Comment by Naia-love** [comment]
alright thank you
