### ISSUE TITLE
Fix Windows files in use error during install

### ISSUE THREAD

**Issue by jagerman** [oxen-io/lokinet#1494]
Windows gets mad if the lokinet gui is already open during install, giving:

![image](https://user-images.githubusercontent.com/4459524/100049382-92e65600-2ded-11eb-966e-d384c812ee17.png)

until you stop the running gui and hit Retry.

The NSIS installer is supposed to be scriptable (that's what the first S stands for) so they ought to be some way to kill the gui if it's running when installing.

**Comment by majestrate** [comment]
we added an option to uninstall the existing lokinet before reinstall. this fixes that.
