### ISSUE TITLE
Fix traffic to an exit node host itself

### ISSUE THREAD

**Issue by jagerman** [oxen-io/lokinet#1499]
Currently when a lokinet instance is in exit providing mode traffic directly to the exit snapp does not work (I believe because we are treating everything as exit traffic and not properly distinguishing between traffic *to* to snapp, and traffic *through* the snapp/exit).

We should fix that: it should be possible to detect snapp traffic by seeing if the source address is the interface address.

**Comment by majestrate** [comment]
this was fixed in #1495
