### ISSUE TITLE
Lokinet on ARM

### ISSUE THREAD

**Issue by rqds12** [oxen-io/lokinet#1518]
**Describe the bug**
Using the repositories to install lokinet, running lokinet throws an error Address already in use.  

**Screenshots Or Logs**

[NFO] [lokinet](803) 2021-01-21 01:01:56.295 GMT [+0.001s] main.cpp:261	Using config file: "/home/pi/.lokinet/lokinet.ini" 
[NFO] [lokinet](803) 2021-01-21 01:01:56.297 GMT [+0.003s] context.cpp:69	lokinet-0.8.2-deb0.8.2-2~deb10 Proof of soon
[NFO] [lokinet](803) 2021-01-21 01:01:56.297 GMT [+0.003s] context.cpp:70	starting up
[NFO] [lokinet](803) 2021-01-21 01:01:56.301 GMT [+0.007s] router/router.cpp:985	Bound RPC server to tcp://127.0.0.1:1190
terminate called after throwing an instance of 'zmq::error_t'
   what(): Address already in use
Aborted

**Device and Operating system (please complete the following information):**
 - OS: Raspbian
-  Device: Raspberry Pi

**Comment by jagerman** [comment]
If you have the lokinet package installed then it configured it to run as a system service (Check with: systemctl status lokinet), so very likely it is already running, hence the error.

**Comment by rqds12** [comment]
Thanks!  I don't know why I didn't think that it was a system service.
