### ISSUE TITLE
Can the loki address be set to a fixed value?

### ISSUE THREAD

**Issue by badboycxcc** [oxen-io/lokinet#1551]
A new xxxx.loki address will be generated every time lokinet is opened. How can I set a fixed loki address? I want to build a web.

**Comment by jagerman** [comment]
In the `[network]` section of lokinet.ini (`/etc/loki/lokinet.ini` by default, for the debian/ubuntu packages, or `~/.lokinet/lokinet.ini` if running it directly) there is a setting `keyfile=`, commented out by default.  If you uncomment it and set this to a filename such as:
`keyfile=my.key`
then it will save the key to that file and persist it on restart.

**Comment by badboycxcc** [comment]
thank  you . I am a Windows system (windows10)。

Jason Rhinelander <notifications@github.com> 于 2021年2月27日周六 下午2:57写道：

**Comment by jagerman** [comment]
~~On Windows I believe it is in `C:\Users\<your username>\AppData\Roaming\lokinet` or possible `...\.lokinet`~~ Nope, see below.

**Comment by majestrate** [comment]
config on windows is at `C:\ProgramData\lokinet\lokinet.ini`

**Comment by badboycxcc** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        thank you very much, is has been resolved.
        
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                badboycxcc
                            
                    
                        
                            
                                    badboycxcc@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 2/27/2021 18:40，Jeff<notifications@github.com> wrote： 



config on windows is at C:\ProgramData\lokinet\lokinet.ini

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by badboycxcc** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            How to check the .loki domain name generated after ubuntu starts the loki service
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                badboycxcc
                            
                    
                        
                            
                                    badboycxcc@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 2/27/2021 18:40，Jeff<notifications@github.com> wrote： 



config on windows is at C:\ProgramData\lokinet\lokinet.ini

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by majestrate** [comment]
`dig @127.3.2.1 -t cname localhost.loki`

**Comment by majestrate** [comment]
on windows it's `nslookup -type=cname localhost.loki 127.0.0.1`

**Comment by badboycxcc** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        thank you
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                badboycxcc
                            
                    
                        
                            
                                    badboycxcc@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 2/28/2021 18:52，Jeff<notifications@github.com> wrote： 



dig @127.3.2.1 -t cname localhost.loki

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
