### ISSUE TITLE
How to dig and buy loki coins?

### ISSUE THREAD

**Issue by badboycxcc** [oxen-io/lokinet#1585]
How to dig and buy loki coins?

**Comment by majestrate** [comment]
[bittrex](https://global.bittrex.com/Market/Index?MarketName=USDT-OXEN) and [kucoin](https://trade.kucoin.com/LOKI-USDT)

**Comment by badboycxcc** [comment]
How to dig it?  Pool address?

Jeff ***@***.***> 于 2021年3月26日周五 下午7:49写道：

**Comment by majestrate** [comment]
the coin is proof of stake you can't mine it.
