### ISSUE TITLE
Allow private network ranges in exit mode

### ISSUE THREAD

**Issue by jagerman** [oxen-io/lokinet#1595]
Lokinet should, in theory, be able to work as a VPN (I mean, the traditional kind, where you connect into a local network, not the the glorified internet proxy that the modern "VPN" term has become synonymous).

We should be able to support this already by just giving a private range, except that @majestrate thinks we have a limitation due to bogon and private ranges being blocked that would prevent this from actually working.

However we could allow an exit to advertise its own range; a default exit would be 0.0.0.0/0, but a private VPN access "exit" could advertise, for example, 10.10.0.0/16 so that when you connect to that exit you get just that IP range routed.  (I have used openvpn in the past in just such a setup and it was very convenient--just turn it on and start talking to my home network while away).

**Comment by majestrate** [comment]
this was implemented and is in dev right now (probably)
