### ISSUE TITLE
The repository 'https://deb.oxen.io ulyssa Release' does not have a Release file.

### ISSUE THREAD

**Issue by Crojav** [oxen-io/lokinet#1641]
`
$ sudo curl -so /etc/apt/trusted.gpg.d/oxen.gpg https://deb.oxen.io/pub.gpg

$ echo "deb https://deb.oxen.io $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/oxen.list
deb https://deb.oxen.io ulyssa main

$ sudo apt update
[sudo] password for:          

Ign:1 http://mintlinux.mirror.wearetriple.com/packages ulyssa InRelease
Hit:2 http://mirror.previder.nl/ubuntu focal InRelease                                                                    
Hit:3 http://mintlinux.mirror.wearetriple.com/packages ulyssa Release                                                     
Get:4 http://mirror.previder.nl/ubuntu focal-updates InRelease [114 kB]                                                   
Get:5 http://ppa.launchpad.net/system76-dev/stable/ubuntu focal InRelease [17.5 kB]                                       
Get:6 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]                                                 
Hit:7 http://archive.canonical.com/ubuntu focal InRelease                                                                 
Get:8 http://mirror.previder.nl/ubuntu focal-backports InRelease [101 kB]                                                 
Hit:10 https://deb.leap.se/client release InRelease                                                                       
Get:11 http://mirror.previder.nl/ubuntu focal-updates/main i386 Packages [474 kB]                                        
Ign:12 https://deb.oxen.io ulyssa InRelease                                                                               
Ign:13 https://deb.loki.network ulyssa InRelease                                                                          
Err:14 https://deb.oxen.io ulyssa Release                                                                     
  404  Not Found [IP: 149.56.148.124 443]
Err:15 https://deb.loki.network ulyssa Release                                                               
  404  Not Found [IP: 149.56.148.124 443]
Get:16 http://mirror.previder.nl/ubuntu focal-updates/main amd64 Packages [982 kB]                           
Get:17 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [24.4 kB]                  
Get:18 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [58.2 kB] 
Ign:19 https://deb.imaginary.stream ulyssa InRelease                                            
Get:20 http://mirror.previder.nl/ubuntu focal-updates/main amd64 DEP-11 Metadata [265 kB]
Get:21 http://mirror.previder.nl/ubuntu focal-updates/universe amd64 Packages [773 kB]  
Err:22 https://deb.imaginary.stream ulyssa Release                             
  404  Not Found [IP: 149.56.148.124 443]
Get:23 http://mirror.previder.nl/ubuntu focal-updates/universe i386 Packages [571 kB]
Get:24 http://mirror.previder.nl/ubuntu focal-updates/universe amd64 DEP-11 Metadata [303 kB]
Get:25 http://mirror.previder.nl/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [2468 B]
Get:26 http://mirror.previder.nl/ubuntu focal-backports/universe amd64 DEP-11 Metadata [1768 B]
Reading package lists... Done                                               
E: The repository 'https://deb.oxen.io ulyssa Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://deb.loki.network ulyssa Release' does not have a Release 
`

**Comment by majestrate** [comment]
in `/etc/apt/sources.list.d/oxen.list` change `ulyssa` to `focal`

**Comment by Crojav** [comment]
deb https://deb.oxen.io focal main

still get the same error:

`Err:14 https://deb.oxen.io ulyssa Release
404 Not Found [IP: 149.56.148.124 443]
Err:15 https://deb.loki.network ulyssa Release
404 Not Found [IP: 149.56.148.124 443]`

**Comment by jagerman** [comment]
What are the contents of /etc/apt/sources.list.d/oxen.list now?

**Comment by Crojav** [comment]
THis is the only line:

`deb https://deb.oxen.io focal main`

**Comment by peepo5** [comment]
Please reopen, I get this too. My version is focal and I get "no release file"

**Comment by jagerman** [comment]
This is not a bug on our side, but rather an issue in Ubuntu rejecting the SSL certificate: https://bugs.launchpad.net/ubuntu/+source/gnutls28/+bug/1928648

There is, in that issue, a notice that they are pushing a fix to the ubuntu security channel, but it doesn't look like that has happened yet.

In the meantime, you can switch the `https://` in the /etc/apt/sources.list.d/oxen.list to `http://` and it should work.  (This isn't an insecure setup, in case that worries you: release and package files are separately signed and verified during package download/installation).

**Comment by peepo5** [comment]
thank you very much :+1:
