### ISSUE TITLE
Embed bootstrap into packages

### ISSUE THREAD

**Issue by jagerman** [oxen-io/lokinet#1654]
Currently the installers call lokinet-bootstrap to download a new bootstrap file during installation.  This isn't great: we're leaking metadata that you just installed lokinet by making an external https request, and will fail if the bootstrap URL is temporarily unreachable.

I think what we should do instead is include a default bootstrap.signed into the package, install it to a system location (e.g. `/usr/share/lokinet/default-mainnet-bootstrap.signed` on Linux), and then use that by default for the bootstrap file when there is no bootstrap.signed in the data directory.  So essentially we'd look for the bootstrap file at:
- if specified in the config file, use that.
- otherwise try DATADIR/bootstrap.signed, if not found, fall back to SYSTEMDATADIR/bootstrap.signed.

We would still ship lokinet-bootstrap, we just wouldn't be invoking it by default.

Obstacles:
- how to specify this default?  We could use some build-time define which would be fine for debs, but I don't think that would work on Windows/Mac where the user can specify the install dir.
- If we need to change the bootstrap servers then we have to issue new binaries.  (We've only had to do this once, when we re-registered all the foundation servers including the old bootstrap node, so issuing a new release with a new default bootstrap file is probably fine).

**Comment by majestrate** [comment]
fixed via #1707
