### ISSUE TITLE
Setting an empty upstream doesn't disable non-Loki DNS

### ISSUE THREAD

**Issue by Efruit** [oxen-io/lokinet#1655]
**Describe the bug**
Setting `upstream=` does not disable DNS resolution for clearnet domains.

**To Reproduce**
1. `lokinet -g`
2. `lokinet-bootstrap`
3. Set `upstream=` in lokinet.ini
4. Start lokinet
5. `dig @127.3.2.1 google.com`

**Device and Operating system:**
 - OS: Linux (Fedora 33)
-  Device: PC
 - Lokinet Version number or Git commit hash: cbb78b52800f3f6e2f9ee0c13e5caa65b9112801

**Comment by majestrate** [comment]
@Efruit try out https://github.com/oxen-io/loki-network/pull/1656 for the fix if you can. let us know if that fixes it on your end (it should)

**Comment by Efruit** [comment]
@majestrate It does, but does it make sense to use `SERVFAIL` for these? Couldn't that trip up resolvers that penalize faulty/unhealthy servers (i.e. load balancers)?

**Comment by majestrate** [comment]
> @majestrate It does, but does it make sense to use `SERVFAIL` for these? Couldn't that trip up resolvers that penalize faulty/unhealthy servers (i.e. load balancers)?

possibly, what would be a better response to send?

**Comment by jagerman** [comment]
SERVFAIL is a bit misnamed, I think for historic reasons, but is supposed to mean "I can't answer that request" in practice and is the right thing to send to tell the system to try the next server.  (NOTFOUND is an authoritative "I know that that domain name doesn't exist").

**Comment by majestrate** [comment]
> SERVFAIL is a bit misnamed, I think for historic reasons, but is supposed to mean "I can't answer that request" in practice and is the right thing to send to tell the system to try the next server. (NOTFOUND is an authoritative "I know that that domain name doesn't exist").

what about REFUSED?

**Comment by jagerman** [comment]
> what about REFUSED?

REFUSED is how a DNS server says "I can answer you, but I choose not to because I don't like you"

**Comment by jagerman** [comment]
(DNS is such an old crusty protocol)

**Comment by majestrate** [comment]
> > what about REFUSED?
> 
> REFUSED is how a DNS server says "I can answer you, but I choose not to because I don't like you"

and NOT IMPLEMENTED?
