### ISSUE TITLE
Windows defender assumes it is a virus

### ISSUE THREAD

**Issue by ghost** [oxen-io/lokinet#1670]
I -ofc- know it is not a virus, but windows defender detects it as a coinminer. Idk if you can contact mcafee or windows to fix this issue.
![Yeni Bit Eşlem Resmi](https://user-images.githubusercontent.com/76991571/122037232-e89f4180-cdc3-11eb-9d6f-a28f4b5bc2c0.jpg)

**Comment by majestrate** [comment]
what do these flags in that report mean exactly?

**Comment by ghost** [comment]
Just says it is a coinminer, I had to disable windows defender to run the exe file.

**Comment by majestrate** [comment]
cve1999-0016 refers to an OS bug that lays outside the scope of what we do: https://www.itsecdb.com/oval/definition/oval/org.mitre.oval/def/5727/A-TCP-SYN-packet-with-target-host-039-s-address-as-both-sou.html
i do not understand how that 20+ year old bug even applies to us, basically it's a massive load of horse shit and FUD. this is why no one takes commercial AVs seriously.

**Comment by majestrate** [comment]
i will keep this issue open in case someone else hits this. this needs to be resolved.

 in the meantime users should consider not using snakeoil or fake security products on their system.

**Comment by ghost** [comment]
Okay; I don't have any av software on the ststem btw, only built in windows defender.

**Comment by majestrate** [comment]
it doesn't really sing praises of windows defender when it marks us as "coin miner" when there is no reason to.

**Comment by ghost** [comment]
Maybe you can try contacting microsoft live support from here
https://support.microsoft.com/en-us/contactus

**Comment by majestrate** [comment]
okay i think i know what was going on, this is an ancient release of lokinet back when we used a small amount of monero's cryptography code for signatures, this would trigger the heuristics warning about coin miner. we dont have this code in lokinet anymore as we use ed25519 signatures instead of monero's custom ecdsa over curve 25519 signatures.
