### ISSUE TITLE
No first hop candidate on Arch Linux (DNS problem?)

### ISSUE THREAD

**Issue by jakecoble** [oxen-io/lokinet#1677]
I'm trying to get lokinet working on my Arch Linux box, and I'm investigating DNS as a potential problem due to #1613 .

Here's the error I'm getting on startup:

```
pathbuilder.cpp:346        endpoint:f1ijytmpdyp4n11f9rchdzuqs69g6wpdi559pih8ak4aib45nbko.loki has no first hop candidate
endpoint.cpp:118        could not publish descriptors for endpoint endpoint:f1ijytmpdyp4n11f9rchdzuqs69g6wpdi559pih8ak4aib45nbko.loki because we couldn't get enough valid introductions
```

I'm using `systemd-resolved` for DNS. This is my /etc/nsswitch.conf:

```
# Name Service Switch configuration file.
# See nsswitch.conf(5) for details.

passwd: files systemd
group: files [SUCCESS=merge] systemd
shadow: files

publickey: files

hosts: files mymachines myhostname resolve [!UNAVAIL=return] dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files
```

For comparison, here is the /etc/nsswitch.conf from an Ubuntu linux container where lokinet *does* work:

```
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         files systemd
group:          files systemd
shadow:         files
gshadow:        files

hosts:          files mdns4_minimal [NOTFOUND=return] dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

Could this problem be caused by DNS configuration? If so, how does lokinet use DNS when it starts up? Where should I look next to solve this problem?

**Comment by jagerman** [comment]
When lokinet starts up it tries to connect to systemd over dbus to tell it to set up systemd-resolved to handle .loki and .snode DNS requests.  Assuming that's working then when it has started up you should see something like this in `resolvectl status`'s output:

```
Link 1343 (lokitun0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 127.3.2.1
       DNS Servers: 127.3.2.1
        DNS Domain: ~loki ~snode
```

**Comment by jagerman** [comment]
(Note that this systemd-resolved support was added in 0.9.2, if I recall correctly).

**Comment by majestrate** [comment]
additionally the aur package `lokinet-bin` does not have systemd support.

**Comment by jagerman** [comment]
> additionally the aur package `lokinet-bin` does not have systemd support.

Oh, in that case the systemd support code won't even get compiled in.

**Comment by jakecoble** [comment]
> additionally the aur package `lokinet-bin` does not have systemd support.

Then lokinet would use resolv.conf, right? Adding `nameserver 127.3.2.1` hasn't helped. Lokinet *is* listening for udp connections on `127.3.2.1:53`.

**Comment by jagerman** [comment]
> Then lokinet would use resolv.conf, right? Adding `nameserver 127.3.2.1` hasn't helped. Lokinet _is_ listening for udp connections on `127.3.2.1:53`.

How to handle DNS gets more complicated in such a case: -- it may well be that *systemd* isn't trying to use resolv.conf at all.  You could try dropping this file into /etc/systemd/resolved.conf.d/00-lokinet.conf and restarting systemd-resolved:
```
[Resolve]
DNS=127.3.2.1
Domains=~
```

Also note that the AUR `lokinet` package *does* have systemd support, it's the `lokinet-bin` one that doesn't.

**Comment by jagerman** [comment]
> because we couldn't get enough valid introductions

This error also shows up when the bootstrap file is missing; did you run `lokinet-bootstrap` to grab it?

**Comment by jakecoble** [comment]
> Also note that the AUR `lokinet` package _does_ have systemd support, it's the `lokinet-bin` one that doesn't.

The lokinet package fails with even *less* information, so I haven't been fiddling with it.

> This error also shows up when the bootstrap file is missing; did you run `lokinet-bootstrap` to grab it?

Yeah, I think the service files are supposed to bootstrap automatically, but I've also run `lokinet-bootstrap` manually and verified that `bootstrap.signed` exists in `/var/lib/lokinet` with no change.

**Comment by tewinget** [comment]
So the lines about "no first hop candidate" and "couldn't get enough valid introductions" aren't unexpected on startup.  Does it keep printing similar lines many seconds to a minute after startup?

**Comment by jakecoble** [comment]
Here's more of the log: https://pastebin.com/PGNZJMfF

Just prints that a bunch.

There doesn't seem to be much more info there, so I'll try rerunning with a higher logging level.

**Comment by jakecoble** [comment]
After some investigation, I'm starting to think that lokinet is running fine, and it's the systemd files that are misconfigured. I'll keep looking.

**Comment by jakecoble** [comment]
Yep, that's the problem. Lokinet is running fine and I'm posting this through the exit.loki exit node. I'll get more details and open a new issue if that's appropriate.
