### ISSUE TITLE
Can't connect to lokinet

### ISSUE THREAD

**Issue by von-dietrich** [oxen-io/lokinet#1679]
Manjaro OS, lokinet-bin 0.9.3-1
```
[daniel@danielcom ~]$ lokinet -g
[daniel@danielcom ~]$ lokinet-bootstrap
downloading https://seed.lokinet.org/lokinet.signed
lokinet successfully bootstrapped
[daniel@danielcom ~]$ lokinet
[NFO] [lokinet](627) 2021-06-23 11:33:53.599 GMT [+0.001s] daemon/lokinet.cpp:264	Using config file: "/home/daniel/.lokinet/lokinet.ini"
[NFO] [lokinet](627) 2021-06-23 11:33:53.599 GMT [+0.001s] llarp/context.cpp:64	lokinet-0.9.3-release A Series of Tubes
[NFO] [lokinet](627) 2021-06-23 11:33:53.599 GMT [+0.001s] llarp/context.cpp:65	starting up
[NFO] [lokinet](627) 2021-06-23 11:33:53.600 GMT [+0.002s] llarp/router/router.cpp:1057	Bound RPC server to tcp://127.0.0.1:1190
[NFO] [lokinet](627) 2021-06-23 11:33:53.600 GMT [+0.002s] llarp/router/router.cpp:588	Loaded 3 bootstrap routers
[NFO] [lokinet](627) 2021-06-23 11:33:53.600 GMT [+0.002s] llarp/router/router.cpp:659	router profiling enabled
[NFO] [lokinet](627) 2021-06-23 11:33:53.600 GMT [+0.002s] llarp/router/router.cpp:662	no profiles file at "/home/daniel/.lokinet/profiles.dat" skipping
[NFO] [lokinet](627) 2021-06-23 11:33:53.600 GMT [+0.002s] llarp/handlers/tun.cpp:145	endpoint:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.loki setting to be reachable by default
[ERR] [](627) 2021-06-23 11:33:53.603 GMT [+0.005s] llarp/handlers/tun.cpp:781	endpoint:6p5uno78i6k3z8dc3f56rarejzqqcyk9ab5jfxi449cogd4edj5o.loki failed to set up network interface: cannot set interface name: Operation not permitted
[ERR] [](627) 2021-06-23 11:33:53.603 GMT [+0.005s] llarp/handlers/tun.cpp:785	endpoint:6p5uno78i6k3z8dc3f56rarejzqqcyk9ab5jfxi449cogd4edj5o.loki failed to obtain network interface
[ERR] [](627) 2021-06-23 11:33:53.603 GMT [+0.005s] llarp/handlers/tun.cpp:841	endpoint:6p5uno78i6k3z8dc3f56rarejzqqcyk9ab5jfxi449cogd4edj5o.loki failed to set up network interface
[ERR] [](627) 2021-06-23 11:33:53.603 GMT [+0.005s] llarp/service/context.cpp:145	default failed to start
[ERR] [](627) 2021-06-23 11:33:53.603 GMT [+0.005s] llarp/router/router.cpp:1163	Failed to start hidden service context
```

lokinet.service
```
[Unit]
Description=LokiNET: Anonymous Network layer thingydoo
Wants=network-online.target
After=network-online.target
Wants=lokinet-bootstrap.service
After=lokinet-bootstrap.service
Wants=lokinet-default-config.service
After=lokinet-default-config.service

[Service]
Type=notify
WatchdogSec=30s
User=lokinet
SyslogIdentifier=lokinet
WorkingDirectory=/var/lib/lokinet
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/lokinet lokinet.ini
Restart=always
RestartSec=5s

# Hardening
PrivateTmp=yes
ProtectHome=yes
ProtectSystem=strict
ProtectHostname=yes
ProtectKernelLogs=yes
ReadWritePaths=/var/lib/lokinet

[Install]
WantedBy=multi-user.target
```

**Comment by majestrate** [comment]
the `lokinet-bin` aur package will not work with a systemd unit with `type=notify` as it is not compiled with sd-notify support. use `type=simple` and remove `WatchdogSec` option. then `systemctl enable --now lokinet`

**Comment by majestrate** [comment]
additionally if you want to be able to run lokinet in the foreground the binary needs to be setcap'd

**Comment by von-dietrich** [comment]
I did as you instructed yet I'm still getting the same error.
```
[daniel@danielcom ~]$ lokinet
[NFO] [lokinet](595) 2021-06-23 12:15:22.536 GMT [+0.001s] daemon/lokinet.cpp:264       Using config file: "/home/daniel/.lokinet/lokinet.ini"
[NFO] [lokinet](595) 2021-06-23 12:15:22.536 GMT [+0.001s] llarp/context.cpp:64 lokinet-0.9.3-release A Series of Tubes
[NFO] [lokinet](595) 2021-06-23 12:15:22.536 GMT [+0.001s] llarp/context.cpp:65 starting up
[NFO] [lokinet](595) 2021-06-23 12:15:22.537 GMT [+0.002s] llarp/router/router.cpp:1057 Bound RPC server to tcp://127.0.0.1:1190
[NFO] [lokinet](595) 2021-06-23 12:15:22.538 GMT [+0.003s] llarp/router/router.cpp:588  Loaded 3 bootstrap routers
[NFO] [lokinet](595) 2021-06-23 12:15:22.538 GMT [+0.003s] llarp/router/router.cpp:659  router profiling enabled
[NFO] [lokinet](595) 2021-06-23 12:15:22.538 GMT [+0.003s] llarp/router/router.cpp:662  no profiles file at "/home/daniel/.lokinet/profiles.dat" skipping
[NFO] [lokinet](595) 2021-06-23 12:15:22.538 GMT [+0.003s] llarp/handlers/tun.cpp:145   endpoint:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.loki setting to be reachable by default
[ERR] [](595) 2021-06-23 12:15:22.543 GMT [+0.008s] llarp/handlers/tun.cpp:781  endpoint:8sy4hdsptwixt9uqi8t5hm5mns7orjc4ywkdffhir8d7txuabnty.loki failed to set up network interface: cannot set interface name: Operation not permitted
[ERR] [](595) 2021-06-23 12:15:22.543 GMT [+0.008s] llarp/handlers/tun.cpp:785  endpoint:8sy4hdsptwixt9uqi8t5hm5mns7orjc4ywkdffhir8d7txuabnty.loki failed to obtain network interface
[ERR] [](595) 2021-06-23 12:15:22.543 GMT [+0.008s] llarp/handlers/tun.cpp:841  endpoint:8sy4hdsptwixt9uqi8t5hm5mns7orjc4ywkdffhir8d7txuabnty.loki failed to set up network interface
[ERR] [](595) 2021-06-23 12:15:22.543 GMT [+0.008s] llarp/service/context.cpp:145       default failed to start
[ERR] [](595) 2021-06-23 12:15:22.543 GMT [+0.008s] llarp/router/router.cpp:1163        Failed to start hidden service context

```
```
  1 [Unit]
  2 Description=LokiNET: Anonymous Network layer thingydoo
  3 Wants=network-online.target
  4 After=network-online.target
  5 Wants=lokinet-bootstrap.service
  6 After=lokinet-bootstrap.service
  7 Wants=lokinet-default-config.service
  8 After=lokinet-default-config.service
  9
 10 [Service]
 11 Type=simple
 12 User=lokinet
 13 SyslogIdentifier=lokinet
 14 WorkingDirectory=/var/lib/lokinet
 15 CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
 16 AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
 17 ExecStart=/usr/bin/lokinet lokinet.ini
 18 Restart=always
 19 RestartSec=5s
 20
 21 # Hardening
 22 PrivateTmp=yes
 23 ProtectHome=yes
 24 ProtectSystem=strict
 25 ProtectHostname=yes
 26 ProtectKernelLogs=yes
 27 ReadWritePaths=/var/lib/lokinet
 28
 29 [Install]
 30 WantedBy=multi-user.target
```

```
[daniel@danielcom ~]$ systemctl start lokinet
[daniel@danielcom ~]$ systemctl status lokinet.service
● lokinet.service - LokiNET: Anonymous Network layer thingydoo
     Loaded: loaded (/usr/lib/systemd/system/lokinet.service; enabled; vendor preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2021-06-23 14:18:51 CEST; 1s ago
    Process: 3095 ExecStart=/usr/bin/lokinet lokinet.ini (code=exited, status=1/FAILURE)
   Main PID: 3095 (code=exited, status=1/FAILURE)
        CPU: 12ms
```

**Comment by jagerman** [comment]
> I did as you instructed yet I'm still getting the same error.

To run as an ordinary user (i.e. directly, rather than through a systemd service) then the binary needs to be modified with setcap to grant it permissions to create network interfaces, etc., using:

```
sudo setcap all=+eip /path/to/lokinet
```

**Comment by von-dietrich** [comment]
> To run as an ordinary user (i.e. directly, rather than through a systemd service) then the binary needs to be modified with setcap to grant it permissions to create network interfaces, etc., using:
> 
> ```
> sudo setcap all=+eip /path/to/lokinet
> ```

```
[daniel@danielcom ~]$ sudo setcap all=+eip /usr/bin/lokinet
[sudo] password for daniel: 
fatal error: Invalid argument
usage: setcap [-h] [-q] [-v] [-n <rootid>] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]

 Note <filename> must be a regular (non-symlink) file.
 -r          remove capability from file
 -           read capability text from stdin
 <capsN>     cap_from_text(3) formatted file capability

 -h          this message and exit status 0
 -q          quietly
 -v          validate supplied capability matches file
 -n <rootid> write a user namespace limited capability
 --license   display the license info
```

**Comment by majestrate** [comment]
> I did as you instructed yet I'm still getting the same error.
> 
> ```
> [daniel@danielcom ~]$ lokinet
> [NFO] [lokinet](595) 2021-06-23 12:15:22.536 GMT [+0.001s] daemon/lokinet.cpp:264       Using config file: "/home/daniel/.lokinet/lokinet.ini"
> [NFO] [lokinet](595) 2021-06-23 12:15:22.536 GMT [+0.001s] llarp/context.cpp:64 lokinet-0.9.3-release A Series of Tubes
> [NFO] [lokinet](595) 2021-06-23 12:15:22.536 GMT [+0.001s] llarp/context.cpp:65 starting up
> [NFO] [lokinet](595) 2021-06-23 12:15:22.537 GMT [+0.002s] llarp/router/router.cpp:1057 Bound RPC server to tcp://127.0.0.1:1190
> [NFO] [lokinet](595) 2021-06-23 12:15:22.538 GMT [+0.003s] llarp/router/router.cpp:588  Loaded 3 bootstrap routers
> [NFO] [lokinet](595) 2021-06-23 12:15:22.538 GMT [+0.003s] llarp/router/router.cpp:659  router profiling enabled
> [NFO] [lokinet](595) 2021-06-23 12:15:22.538 GMT [+0.003s] llarp/router/router.cpp:662  no profiles file at "/home/daniel/.lokinet/profiles.dat" skipping
> [NFO] [lokinet](595) 2021-06-23 12:15:22.538 GMT [+0.003s] llarp/handlers/tun.cpp:145   endpoint:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.loki setting to be reachable by default
> [ERR] [](595) 2021-06-23 12:15:22.543 GMT [+0.008s] llarp/handlers/tun.cpp:781  endpoint:8sy4hdsptwixt9uqi8t5hm5mns7orjc4ywkdffhir8d7txuabnty.loki failed to set up network interface: cannot set interface name: Operation not permitted
> [ERR] [](595) 2021-06-23 12:15:22.543 GMT [+0.008s] llarp/handlers/tun.cpp:785  endpoint:8sy4hdsptwixt9uqi8t5hm5mns7orjc4ywkdffhir8d7txuabnty.loki failed to obtain network interface
> [ERR] [](595) 2021-06-23 12:15:22.543 GMT [+0.008s] llarp/handlers/tun.cpp:841  endpoint:8sy4hdsptwixt9uqi8t5hm5mns7orjc4ywkdffhir8d7txuabnty.loki failed to set up network interface
> [ERR] [](595) 2021-06-23 12:15:22.543 GMT [+0.008s] llarp/service/context.cpp:145       default failed to start
> [ERR] [](595) 2021-06-23 12:15:22.543 GMT [+0.008s] llarp/router/router.cpp:1163        Failed to start hidden service context
> ```
> 
> ```
>   1 [Unit]
>   2 Description=LokiNET: Anonymous Network layer thingydoo
>   3 Wants=network-online.target
>   4 After=network-online.target
>   5 Wants=lokinet-bootstrap.service
>   6 After=lokinet-bootstrap.service
>   7 Wants=lokinet-default-config.service
>   8 After=lokinet-default-config.service
>   9
>  10 [Service]
>  11 Type=simple
>  12 User=lokinet
>  13 SyslogIdentifier=lokinet
>  14 WorkingDirectory=/var/lib/lokinet
>  15 CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
>  16 AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
>  17 ExecStart=/usr/bin/lokinet lokinet.ini
>  18 Restart=always
>  19 RestartSec=5s
>  20
>  21 # Hardening
>  22 PrivateTmp=yes
>  23 ProtectHome=yes
>  24 ProtectSystem=strict
>  25 ProtectHostname=yes
>  26 ProtectKernelLogs=yes
>  27 ReadWritePaths=/var/lib/lokinet
>  28
>  29 [Install]
>  30 WantedBy=multi-user.target
> ```
> 
> ```
> [daniel@danielcom ~]$ systemctl start lokinet
> [daniel@danielcom ~]$ systemctl status lokinet.service
> ● lokinet.service - LokiNET: Anonymous Network layer thingydoo
>      Loaded: loaded (/usr/lib/systemd/system/lokinet.service; enabled; vendor preset: disabled)
>      Active: activating (auto-restart) (Result: exit-code) since Wed 2021-06-23 14:18:51 CEST; 1s ago
>     Process: 3095 ExecStart=/usr/bin/lokinet lokinet.ini (code=exited, status=1/FAILURE)
>    Main PID: 3095 (code=exited, status=1/FAILURE)
>         CPU: 12ms
> ```

`sudo systemctl daemon-reload`
then
`sudo systemctl restart lokinet`

**Comment by von-dietrich** [comment]
> `sudo systemctl daemon-reload`
> then
> `sudo systemctl restart lokinet`

```
[daniel@danielcom ~]$ sudo systemctl daemon-reload
[daniel@danielcom ~]$ sudo systemctl restart lokinet
[daniel@danielcom ~]$ lokinet
[NFO] [lokinet](907) 2021-06-23 12:47:22.101 GMT [+0.000s] daemon/lokinet.cpp:264       Using config file: "/home/daniel/.lokinet/lokinet.ini"
[NFO] [lokinet](907) 2021-06-23 12:47:22.102 GMT [+0.001s] llarp/context.cpp:64 lokinet-0.9.3-release A Series of Tubes
[NFO] [lokinet](907) 2021-06-23 12:47:22.102 GMT [+0.001s] llarp/context.cpp:65 starting up
[NFO] [lokinet](907) 2021-06-23 12:47:22.102 GMT [+0.001s] llarp/router/router.cpp:1057 Bound RPC server to tcp://127.0.0.1:1190
[NFO] [lokinet](907) 2021-06-23 12:47:22.103 GMT [+0.002s] llarp/router/router.cpp:588  Loaded 3 bootstrap routers
[NFO] [lokinet](907) 2021-06-23 12:47:22.103 GMT [+0.002s] llarp/router/router.cpp:659  router profiling enabled
[NFO] [lokinet](907) 2021-06-23 12:47:22.103 GMT [+0.002s] llarp/router/router.cpp:662  no profiles file at "/home/daniel/.lokinet/profiles.dat" skipping
[NFO] [lokinet](907) 2021-06-23 12:47:22.103 GMT [+0.002s] llarp/handlers/tun.cpp:145   endpoint:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.loki setting to be reachable by default
[ERR] [](907) 2021-06-23 12:47:22.105 GMT [+0.004s] llarp/handlers/tun.cpp:781  endpoint:kfgy4u6xxktbt97b78n4nnjq55w4xrij16zbtr1koimsxioozc4o.loki failed to set up network interface: cannot set interface name: Operation not permitted
[ERR] [](907) 2021-06-23 12:47:22.105 GMT [+0.004s] llarp/handlers/tun.cpp:785  endpoint:kfgy4u6xxktbt97b78n4nnjq55w4xrij16zbtr1koimsxioozc4o.loki failed to obtain network interface
[ERR] [](907) 2021-06-23 12:47:22.105 GMT [+0.004s] llarp/handlers/tun.cpp:841  endpoint:kfgy4u6xxktbt97b78n4nnjq55w4xrij16zbtr1koimsxioozc4o.loki failed to set up network interface
[ERR] [](907) 2021-06-23 12:47:22.105 GMT [+0.004s] llarp/service/context.cpp:145       default failed to start
[ERR] [](907) 2021-06-23 12:47:22.105 GMT [+0.004s] llarp/router/router.cpp:1163        Failed to start hidden service context
```

**Comment by majestrate** [comment]
> > `sudo systemctl daemon-reload`
> > then
> > `sudo systemctl restart lokinet`
> 
> ```
> [daniel@danielcom ~]$ sudo systemctl daemon-reload
> [daniel@danielcom ~]$ sudo systemctl restart lokinet
> [daniel@danielcom ~]$ lokinet
> [NFO] [lokinet](907) 2021-06-23 12:47:22.101 GMT [+0.000s] daemon/lokinet.cpp:264       Using config file: "/home/daniel/.lokinet/lokinet.ini"
> [NFO] [lokinet](907) 2021-06-23 12:47:22.102 GMT [+0.001s] llarp/context.cpp:64 lokinet-0.9.3-release A Series of Tubes
> [NFO] [lokinet](907) 2021-06-23 12:47:22.102 GMT [+0.001s] llarp/context.cpp:65 starting up
> [NFO] [lokinet](907) 2021-06-23 12:47:22.102 GMT [+0.001s] llarp/router/router.cpp:1057 Bound RPC server to tcp://127.0.0.1:1190
> [NFO] [lokinet](907) 2021-06-23 12:47:22.103 GMT [+0.002s] llarp/router/router.cpp:588  Loaded 3 bootstrap routers
> [NFO] [lokinet](907) 2021-06-23 12:47:22.103 GMT [+0.002s] llarp/router/router.cpp:659  router profiling enabled
> [NFO] [lokinet](907) 2021-06-23 12:47:22.103 GMT [+0.002s] llarp/router/router.cpp:662  no profiles file at "/home/daniel/.lokinet/profiles.dat" skipping
> [NFO] [lokinet](907) 2021-06-23 12:47:22.103 GMT [+0.002s] llarp/handlers/tun.cpp:145   endpoint:yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.loki setting to be reachable by default
> [ERR] [](907) 2021-06-23 12:47:22.105 GMT [+0.004s] llarp/handlers/tun.cpp:781  endpoint:kfgy4u6xxktbt97b78n4nnjq55w4xrij16zbtr1koimsxioozc4o.loki failed to set up network interface: cannot set interface name: Operation not permitted
> [ERR] [](907) 2021-06-23 12:47:22.105 GMT [+0.004s] llarp/handlers/tun.cpp:785  endpoint:kfgy4u6xxktbt97b78n4nnjq55w4xrij16zbtr1koimsxioozc4o.loki failed to obtain network interface
> [ERR] [](907) 2021-06-23 12:47:22.105 GMT [+0.004s] llarp/handlers/tun.cpp:841  endpoint:kfgy4u6xxktbt97b78n4nnjq55w4xrij16zbtr1koimsxioozc4o.loki failed to set up network interface
> [ERR] [](907) 2021-06-23 12:47:22.105 GMT [+0.004s] llarp/service/context.cpp:145       default failed to start
> [ERR] [](907) 2021-06-23 12:47:22.105 GMT [+0.004s] llarp/router/router.cpp:1163        Failed to start hidden service context
> ```

`systemctl status lokinet`

there is no need to run it in the foreground as it should be running via systemd now.

**Comment by von-dietrich** [comment]
> `systemctl status lokinet`

```
● lokinet.service - LokiNET: Anonymous Network layer thingydoo
     Loaded: loaded (/usr/lib/systemd/system/lokinet.service; enabled; vendor preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2021-06-23 15:01:56 CEST; 2s ago
    Process: 7494 ExecStart=/usr/bin/lokinet lokinet.ini (code=exited, status=1/FAILURE)
   Main PID: 7494 (code=exited, status=1/FAILURE)
        CPU: 34ms
```

```
cze 23 15:04:02 danielcom lokinet[7610]: [NFO] [lokinet](383) 2021-06-23 13:04:02.494 GMT [+0.000s] daemon/lokinet.cpp:264        Using config file: "lokinet.ini"
cze 23 15:04:02 danielcom lokinet[7610]: [ERR] [lokinet](383) 2021-06-23 13:04:02.494 GMT [+0.000s] daemon/lokinet.cpp:293        Fatal: caught exception while running: Config file parsing failed
cze 23 15:04:02 danielcom lokinet[7610]: main thread threw exception: Config file parsing failed
cze 23 15:04:02 danielcom systemd[1]: lokinet.service: Main process exited, code=exited, status=1/FAILURE
```
