### ISSUE TITLE
Can't add services section to lokinet.ini

### ISSUE THREAD

**Issue by vecna13** [oxen-io/lokinet#1684]
I'm running lokinet-0.9.4-deb0.9.4-1~deb11 (installed from package on Debian Testing/Bullseye).

I want to run multiple SNApps using different .loki addresses. Based on https://docs.loki.network/Lokinet/Guides/LokinetConfig/ I think the way to go about this is to add a `[service]` block to my lokinet.ini and specify different keyfiles for different services.

When I try to add services to my lokinet.ini like...

```
[services]
myservice=/var/lib/lokinet/myservice/service.ini
```

...lokinet fails to run. journalctl tells me "Error trying to init and parse config from file: unrecognized section [services]"

```
Jun 26 21:14:03 hostname systemd[1]: Starting LokiNET: Anonymous Network layer thingydoo, client...
Jun 26 21:14:03 hostname lokinet[1048566]: [NFO] [lokinet](383) 2021-06-27 02:14:03.793 GMT [+0.002s] daemon/lokinet.cpp:264        Using config file: "/var/lib/lokinet/lokinet.ini"
Jun 26 21:14:03 hostname lokinet[1048566]: [ERR] [lokinet](383) 2021-06-27 02:14:03.793 GMT [+0.002s] llarp/config/config.cpp:1229        Error trying to init and parse config from file: unrecognized section [services]
Jun 26 21:14:03 hostname lokinet[1048566]: [ERR] [lokinet](383) 2021-06-27 02:14:03.793 GMT [+0.002s] daemon/lokinet.cpp:293        Fatal: caught exception while running: Config file parsing failed
Jun 26 21:14:03 hostname lokinet[1048566]: main thread threw exception: Config file parsing failed
Jun 26 21:14:03 hostname systemd[1]: lokinet.service: Main process exited, code=exited, status=1/FAILURE
Jun 26 21:14:03 hostname systemd[1]: lokinet.service: Failed with result 'exit-code'.
Jun 26 21:14:03 hostname systemd[1]: Failed to start LokiNET: Anonymous Network layer thingydoo, client.
```

Has this option been removed? Is there a supported way to use more than one .loki address/key on the same machine?

Thanks!

**Comment by majestrate** [comment]
this option was removed, it can still in theory be wired up but it was removed because the way it was exposed to the user was poorly done.

**Comment by jagerman** [comment]
The way that we're doing this now is to run multiple lokinets at once, one for each snapp.

The easiest way to make this work is to use a `/etc/systemd/system/lokinet@.service` file containing:
```ini
[Unit]
Description=LokiNET: Anonymous Network layer thingydoo, client (%i)
After=network-online.target
Wants=network-online.target
PartOf=lokinet-snapps.target
AssertFileNotEmpty=/var/lib/lokinet/snapp-%i/lokinet.ini

[Service]
User=_lokinet
Type=notify
WatchdogSec=30s
SyslogIdentifier=lokinet-%i
WorkingDirectory=/var/lib/lokinet/snapp-%i
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/lokinet /var/lib/lokinet/router-%i/lokinet.ini
Environment=LOKINET_NETID=lokinet
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
```
then you generate and customize a config for each instance with:

```
sudo lokinet -c -g /var/lib/lokinet/lokinet-xyz/lokinet.ini
sudo lokinet-bootstrap mainnet /var/lib/lokinet/lokinet-xyz/bootstrap.signed
```
where "xyz" can be whatever you want, and is distinct for each one.

You will have to make a couple edits to each of the /var/lib/lokinet/lokinet-xyz/lokinet.ini files:
- in the `[dns]` section specify a different `bind=` value.  Any random IP addresses from 127.x.y.z will work without exposing anything.
- in the `[api]` section specify a different port for the `bind=` parameter for each snapp.  E.g. `bind=tcp://127.0.0.1:11900` and then `:11901`, etc.
- in the `[network]` section specify a unique `ifaddr=` range for each one.  I'd suggesting starting at `ifaddr=172.16.0.1/16` and then `172.17.0.1/16` for the next one, up to `172.31.0.1/16`.  (If you need more than 16 that you can started allocating in the `10.x.0.1/16` range.)  This isn't strictly necessary, but if you don't do it each lokinet will likely end up using a different random range on restart.

You then enable at control the individual services using:
```
sudo systemctl enable lokinet-snapp@xyz
sudo systemctl start lokinet-snapp@xyz
sudo systemctl stop lokinet-snapp@xyz
sudo journalctl -u lokinet-snapp@xyz -af  # watch logs
sudo systemctl restart lokinet-snapps.target  # restarts *all* lokinet-snapp@whatever's at once.
```
etc.

**Comment by vecna13** [comment]
Fantastic, thank you!
