### ISSUE TITLE
lokinet execution error

### ISSUE THREAD

**Issue by unmellow** [oxen-io/lokinet#1690]
**Describe the bug**
the lokinet aur package (not lokinet-bin) gets an execution error when you execute it
this does not happen with lokinet -g or lokinet-bootstrap

(also trying to use the service file fails and it claims that it got a sig stop but i think the other issue causes this)

**To Reproduce**
execute:
```sh
paru -S lokinet (or aur handler of your choice)
lokinet -g && lokinet-bootstrap
lokinet
```
**Screenshots Or Logs**
```sh
[NFO] [lokinet](207) 2021-07-01 07:12:53.589 GMT [+0.000s] daemon/lokinet.cpp:264            using config file: "/home/meltonmb/.lokinet/lokinet.ini"
/usr/include/c++/11.1.0/string_view:234: constexpr const value_type& std::basic_string_view<_CharT, _Traits>::operator[](std::basic_string_view<_CharT, _Traits>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; std::basic_string_view<_CharT, _Traits>::const_reference = const char&; std::basic_string_view<_CharT, _Traits>::size_type = long unsigned int]: Assertion '__pos < this->_M_len' failed.
ion: pipeline execution error: process (1602002) had a core dump
```
that is all that prints

**Device and Operating system (please complete the following information):**
 - OS: [manjaro]
-  Device: [ custom ryzen 5 pc]
 - Lokinet Version number or Git commit hash: 0.9.4

**Comment by unmellow** [comment]
lokinet-bin has it's own bugs but thats a whole other can of worms
it gets files from https://oxen.rocks/oxen-io/loki-network/

where as lokinet gets them from github

**Comment by majestrate** [comment]
what compiler version is in use?

**Comment by unmellow** [comment]
gcc 11.1.0 (the latest i think)

**Comment by unmellow** [comment]
do to computer issues i had to reinstall manjaro still having exactly the same problem

**Comment by majestrate** [comment]
fixed in https://github.com/oxen-io/lokinet/commit/4f1bd14d3c64bfec63f8574cc88790b390956d14
