### ISSUE TITLE
while running lokinet  --router

### ISSUE THREAD

**Issue by omg-itsme** [oxen-io/lokinet#1695]
[ERR] [lokinet](858) 2021-07-08 11:27:50.412 GMT [+0.015s] daemon/lokinet.cpp:293	Fatal: caught exception while running: service node enabled but could not find a public IP to bind to; you need to set the public-ip= and public-port= options

**Comment by jagerman** [comment]
Lokinet tries to look for a public IP to bind to (and advertise to other peers), but if it can't (e.g. because you're behind NAT or a more complicated proxied setup) then you need to set the public-ip= and public-port= options in lokinet.ini with your publicly accessible IP address and port.
