### ISSUE TITLE
issue when running lokinet --router

### ISSUE THREAD

**Issue by trever001** [oxen-io/lokinet#1696]
[WRN] [lokinet](126) 2021-07-09 10:54:08.886 GMT [+0.005s] llarp/router/router.cpp:454	!!!! you have manually set netid to be 'gamma' which does not equal 'lokinet' you will run as a different network, good luck and don't forget: something something MUH traffic shape correlation !!!!
[NFO] [lokinet](126) 2021-07-09 10:54:08.886 GMT [+0.005s] llarp/router/router.cpp:583	Loaded 1 bootstrap routers
[NFO] [lokinet](126) 2021-07-09 10:54:08.886 GMT [+0.005s] llarp/router/router.cpp:654	router profiling enabled
[NFO] [lokinet](126) 2021-07-09 10:54:08.886 GMT [+0.005s] llarp/router/router.cpp:657	no profiles file at "/home/user/.lokinet/profiles.dat" skipping
[WRN] [](126) 2021-07-09 10:54:08.887 GMT [+0.006s] llarp/router/router.cpp:249	Obtained lokid identity keys
 addrs.empty() 1
[ERR] [](126) 2021-07-09 10:54:08.887 GMT [+0.006s] llarp/router/router.cpp:1088	we are configured as relay but have no reachable addresses

**Comment by majestrate** [comment]
what does your config contain?

**Comment by trever001** [comment]
[router]
# Configuration for routing activity.


# Network ID; this is 'lokinet' for mainnet, 'gamma' for testnet.
netid=gamma

# Minimum number of routers lokinet will attempt to maintain connections to.
min-connections=6

# Maximum number (hard limit) of routers lokinet will be connected to at any time.
max-connections=60

# Optional directory for containing lokinet runtime data. This includes generated
# private keys.
data-dir=/home/user/.lokinet

# For complex network configurations where the detected IP is incorrect or non-public
# this setting specifies the public IP at which this router is reachable. When
# provided the public-port option must also be specified.
public-ip=127.0.0.1

# When specifying public-ip=, this specifies the public UDP port at which this lokinet
# router is reachable. Required when public-ip is used.
public-port=1190

# The number of threads available for performing cryptographic functions.
# The minimum is one thread, but network performance may increase with more.
# threads. Should not exceed the number of logical CPU cores.
# 0 means use the number of logical CPU cores detected at startup.
worker-threads=0

# Filename in which to store the router contact file
# An absolute path is used as-is, otherwise relative to 'data-dir'.
contact-file=self.signed

# Filename in which to store the encryption private key
# An absolute path is used as-is, otherwise relative to 'data-dir'.
encryption-privkey=encryption.key

# Filename in which to store the identity private key
# An absolute path is used as-is, otherwise relative to 'data-dir'.
ifname=enp0s25

# Local IP and range for lokinet traffic. For example, 172.16.0.1/16 to use
# 172.16.0.1 for this machine and 172.16.x.y for remote peers. If omitted then
# lokinet will attempt to find an unused private range.
ifaddr=192.168.1.37/24

**Comment by trever001** [comment]
[router]

netid=gamma


min-connections=6


max-connections=60


data-dir=/home/user/.lokinet


public-ip=127.0.0.1


public-port=1190


worker-threads=0


contact-file=self.signed


encryption-privkey=encryption.key


ifname=enp0s25

ifaddr=192.168.1.37/24

**Comment by majestrate** [comment]
the public ip cannot be on a private address range, it must be a
publicly routable ip address.
