### ISSUE TITLE
(PROPOSAL) Wireguard implementation

### ISSUE THREAD

**Issue by cryptoxico** [oxen-io/lokinet#1699]
Wireguard for VPN protocol is more adapted for lokinet protocol than OpenVPN and especially for portables devices

Benefits:
1/ It's a very light code (4000 lines) 
2/ More faster than OpenVPN but a little more latency
3/ More secure ( ChaCha20 encryption is designed for streaming communications)
4/ NordVPN forked the protocol, we can do the same with a magic lokinet touch ane correct his faults

Problems:
1/The code is recent (Stable version was released at march 2020)
2/Support correctly only on Linux (user space on Win10 /android/IOS/OSX) but not the on nordlynx protocol (nordvpn)

**Comment by majestrate** [comment]
lokinet is itself a "VPN protocol" already, sort of.
wireguard is kernel mode on linux and were are not io bound on linux at the moment using tun/tap.
on windows their driver is called wintun, i am thinking about moving to use it on windows but their licensing is rather dubiously worded.
