### ISSUE TITLE
Failed to fetch 'https://seed.lokinet.org/lokinet.signed'

### ISSUE THREAD

**Issue by J053Fabi0** [oxen-io/lokinet#1706]
**Describe the bug**
That is all it says: `failed to fetch 'https://seed.lokinet.org/lokinet.signed' HTTP 0`, when running `lokinet-bootstrap`.

**To Reproduce**

1. Install it on Arch Linux by `yay -S lokinet-bin`.
2. Run `lokinet-bootstrap`

**Screenshots Or Logs**
[![1.png](https://i.postimg.cc/nzchppVW/1.png)](https://postimg.cc/Y4ZHxcWN)

**Device and Operating system (please complete the following information):**
 - OS: Arch Linux.
-  Device: X1 Yoga Thinkpad.
 - Lokinet Version number or Git commit hash: 0.9.5-1.

**Comment by majestrate** [comment]
end users are not to use the ci produced lokinet binaries as clients as the x509 ca stuff cannot be done in a static way. they exist as an artifact for use from a long deprecated setup that we don't want to support (but have to).

**Comment by majestrate** [comment]
you can replace the `lokinet-bootstrap` binary with a shell script that does `wget -O /var/lib/lokinet/bootstrap.signed https://seed.lokinet.org/lokinet.signed`
we only moved to a binary executable because of windows.
