### ISSUE TITLE
Proof of history can be interesting for a better synchronisation on the network ? 

### ISSUE THREAD

**Issue by cryptoxico** [oxen-io/lokinet#1710]

**Comment by majestrate** [comment]
what is 'proof of history'?

**Comment by 144** [comment]
> 
> 
> what is 'proof of history'?

I think they meant this thing, can't really relate on how does it work cause I wasn't digging in its documentation
https://medium.com/solana-labs/proof-of-history-a-clock-for-blockchain-cf47a61a9274
https://en.cryptonomist.ch/2019/08/18/proof-of-history-consensus-algorithm/

**Comment by KeeJef** [comment]
If its related to the blockchain this issue should be moved to Oxen core
