### ISSUE TITLE
Exit nodes shouldn't be service nodes

### ISSUE THREAD

**Issue by imzooming** [oxen-io/lokinet#1711]
I tried setting up an exit node on a NAT only VPS to be cheap and sneaky, but just found out I had to run a service node to run exit node.

There are several drawbacks to the current design:
- this will limit the number of exit nodes because the high cost of entry and limited service node numbers
- combining exit node and service node(where everyone's money is at) is a security and regulation concern
- because the IP of service nodes are well known, they can be put in a spam filter so when visiting many clearnet websites, spam blockers will hinder browsing. For example, it's very difficult to visit cloudflare protected sites with Tor and watching YouTube with Tor is impossible.
- calculation of rewards of pooled service nodes is more complex once exit node marketplace is implemented, do stakers deserve the exit node income? that's difficult to answer, if yes then the operator fee should be higher and there should be a "exit node" label... it's not a clean solution

### Allowing users to run exit nodes like registering SNAPPs will solve all these problems. The marketplace can be setup so that the a part of the income of exit nodes goes to all service nodes.

I don't know how to set labels, this is not a bug but an enhancement, so janny help

**Comment by majestrate** [comment]
exit nodes currently only can run as snapps, exit nodes cannot be run on service nodes. whoever told you the inverse was wrong.

**Comment by majestrate** [comment]
the desired behavior is already the default.

**Comment by imzooming** [comment]
I read that it's optional for service nodes to become exit nodes
https://docs.loki.network/ServiceNodes/ServiceNodeFunctions/#exit-nodes

how do I setup an exit node on NAT only VPS? do I have to run the regular service node daemon but with a different config or something?

**Comment by majestrate** [comment]
https://github.com/oxen-io/lokinet/blob/dev/docs/exit-setup.md

**Comment by majestrate** [comment]
you only need a lokinet client and the above exit config snippets

**Comment by imzooming** [comment]
This is pretty insane
how do I set an auth code?

**Comment by majestrate** [comment]
auth codes require an external daemon that does the actual auth code validation logic, there is a demo of a (toy) pay based exit here (not production ready) https://github.com/majestrate/lokinet-exit-provider

**Comment by imzooming** [comment]
WHAT? AN EXAMPLE PAY BASED AUTH CODE DAEMON?
this is getting ridiculously insane, I suppose gotta buy every single dip before some hedgie understands this ill-documented project
thank you man
