### ISSUE TITLE
DNS leaking

### ISSUE THREAD

**Issue by imzooming** [oxen-io/lokinet#1718]
DNS request first goes to 127.0.0.53, then it goes to 127.3.2.1 after a few seconds and resolves.
When it went to 127.0.0.53 it leaked.

**How to reproduce the problem**
1. Fresh install of Ubuntu 20.04 inside KVM, host system is Arch
https://releases.ubuntu.com/20.04/ubuntu-20.04.2.0-desktop-amd64.iso.torrent
2. Followed [Oxen Docs](https://docs.oxen.io/products-built-on-oxen/lokinet/guides/linux-gui-install-guide) closely, could not resolve to 127.3.2.1 by default
3. Went to [Linux Troubleshooting](https://docs.oxen.io/products-built-on-oxen/lokinet/guides/linux-troubleshooting) and added
`nameserver 127.3.2.1` to `/etc/resolvconf/resolv.conf.d/head`
4. Ran `sudo resolvconf -u` and `systemctl restart lokinet`
5. nslookup whoami.loki, it goes through 127.0.0.53 and could not be resolved, after repeated tries, it goes through 127.3.2.1 and resolves
6. Wireshark the host, filter dns
7. nslookup another .loki address, same behavior in step 5
8. check wireshark, it's leaked

**Comment by jagerman** [comment]
This is intended behaviour; 127.0.0.53 is the systemd-resolved resolver stub, which is configured by lokinet to send .loki and .snode DNS requests to lokinet (at 127.3.2.1), and when you turn exit mode on, to send *all* DNS lookups to lokinet.

If systemd-resolved is leaking requests by making DNS requests to your configured local network DNS server then *that* is a leak, but the request going to 127.0.0.53 first (before 127.3.2.1) is not.

**Comment by imzooming** [comment]
> If systemd-resolved is leaking requests by making DNS requests to your configured local network DNS server then _that_ is a leak, but the request going to 127.0.0.53 first (before 127.3.2.1) is not

Except I didn't configure any local DNS server myself, it's a fresh install and I followed the Oxen docs, and when it went though 127.0.0.53 it did leak, it was detected by wireshark on the kvm host
![leak1](https://user-images.githubusercontent.com/88461054/130331996-0a120086-5bed-44d5-a84d-32fe6c482c40.png)
The second nslookup came from 127.3.2.1 and it doesn't leak

Just reproduce it and see for yourself

**Comment by majestrate** [comment]
> > If systemd-resolved is leaking requests by making DNS requests to your configured local network DNS server then _that_ is a leak, but the request going to 127.0.0.53 first (before 127.3.2.1) is not
> 
> Except I didn't configure any local DNS server myself, it's a fresh install and I followed the Oxen docs, and when it went though 127.0.0.53 it did leak, it was detected by wireshark on the kvm host
> ![leak1](https://user-images.githubusercontent.com/88461054/130331996-0a120086-5bed-44d5-a84d-32fe6c482c40.png)
> The second nslookup came from 127.3.2.1 and it doesn't leak
> 
> Just reproduce it and see for yourself

which interface was this capture done from?

**Comment by imzooming** [comment]
> which interface was this capture done from?

From the main lan interface of the computer

I found the problem
The fresh install of the Ubuntu by default sets the DNS of wired connection to auto
![problem](https://user-images.githubusercontent.com/88461054/130724621-7b795b71-b711-4029-804f-883dd93608c4.png)
Toggling this off stops the leak.
Better mention this in Oxen Docs, if the configuration in command line transfers the settings to GUI would be great, I don't know what that toggle button changes to which configuration files.

## However another problem came up
Now clearnet DNS cannot be resolved after this fix, .loki sites work just fine
```
~$ nslookup speedtest.net
;; Got SERVFAIL reply from 127.3.2.1, trying next server
Server:		127.0.0.53
Address:	127.0.0.53#53

** server can't find speedtest.net: SERVFAIL
```
I changed a couple of exit nodes but it didn't help

**Comment by jagerman** [comment]
> Now clearnet DNS cannot be resolved after this fix, .loki sites work just fine

This is very likely #1715.  As a temporary workaround try adding `upstream=1.1.1.1` into the config file (this *should* be the default but there's a bug in the current version preventing the default from being applied properly).

**Comment by imzooming** [comment]
> try adding `upstream=1.1.1.1`

After adding that to the `/etc/loki/lokinet.ini`, exit resolution worked.

Now the setup is perfect, thanks.

You guys seriously need to update the docs, if the user left the auto DNS switch by default their DNS would be totally leaked, he would never know unless he wiresharked.
