### ISSUE TITLE
Lokinet fails to set DNS on other init systems.

### ISSUE THREAD

**Issue by Lavember** [oxen-io/lokinet#1730]
Using Artix Runit, lokinet fails in regards to setting up a dns for connecting to .loki sites. It tries to use "systemd-resolved" apparently but fails since I do not have it in my system.
![image](https://user-images.githubusercontent.com/24517211/132263501-04c04bbd-c82d-402f-84aa-e86b41ceabf2.png)

**Comment by jagerman** [comment]
This isn't a fatal error, but without systemd-resolved you must configure the system's DNS resolver to query `127.3.2.1` when lokinet starts in order for resolution to work properly.

**Comment by Lavember** [comment]
Thanks! I'll try that.

**Comment by jagerman** [comment]
Closing due to lack of response.
