### ISSUE TITLE
Create rpc call for get_stats

### ISSUE THREAD

**Issue by darcys22** [oxen-io/lokinet#1734]
For the GUI frontend we are currently calling a dump_stats endpoint which sends too much information for the frontend.

Design a smaller endpoint to send only relevant information for the frontend to query

**Comment by majestrate** [comment]
for calculating global in/out bandwidth you can access `llarp::AbstractRouter`'s `ILinkManager` iterate all links, iterate all peers on each link and sum up the total current bandwidth use from each session. you'd need to add a method to `ILinkSession` for getting a session's current bandwidth use.
