### ISSUE TITLE
Release New MacOS Binaries 

### ISSUE THREAD

**Issue by cl0vrfi3ld** [oxen-io/lokinet#1737]
First off, I completely understand and agree with why the team doesn't like mac/apple, but it would be amazing to be able to use Lokinet on my personal computer. I have a paid dev account and have attempted building from source, but cli codesigning and exporting certs is doing my head in. The older released binaries and the pkg have been broken for me, both of which being unable to find `exit.loki`, or any other loki address really. It would be immensely helpful if the mac gui was updated to the latest version and added to a release, and/or if the docs were updated with pointers on how to properly sign things. Cheers!

**Comment by majestrate** [comment]
we have been rewriting the macos version and it will be distributed via the app store when it is ready for release.

**Comment by majestrate** [comment]
also, refer to the macos readme [here](https://github.com/oxen-io/lokinet/blob/dev/contrib/macos/README.txt) on why compiling from source on macos is basically impossible now for mac users.

**Comment by majestrate** [comment]
if you find this disagreeable consider using a platform that allows you to trivially compile from source, apple doesn't allow it anymore and it's their choice not ours.

**Comment by cl0vrfi3ld** [comment]
i wish i could leave macos, but I unfortunately have to do some stuff with iOS from time-to-time so I'm stuck. Good to hear though that its coming to the app store, thanks for the heads-up.

**Comment by majestrate** [comment]
If it was my call I would have just dropped support for all apple targets as it is most definitely not worth the development effort given the number and quality of apple users.

**Comment by filipesmedeiros** [comment]
@majestrate as a macbook user (i think it's the best mix of usability, security and performance) i would love to keep going on a mac. but i read your readme, and i hated it. i want to change now. i don't want to support this kind of behaviour, even if hidden behind security and safety justifications by apple.

so my question to you is: what's the best option for me? windows? or some linux distro? i want to have a good experience, look at pretty buttons and colors _while_ being safe and hidden from stupid corporations

can you please help? i'd love to use lokinet then!

**Comment by majestrate** [comment]
i cannot tell you what OS is right for your use case. you can still use macos but run lokinet on your gateway, push dns via dhcp to the lan and force all internet traffic over an exit, that is the "best" way to use lokinet if you ask me, you dont have to care what os you use as anything on that lan will use lokinet.

**Comment by filipesmedeiros** [comment]
That's amazing! I will investigate but small question: can a rasp pi handle normal home traffic? Netflix, YouTube, gaming etc?

**Comment by majestrate** [comment]
> That's amazing! I will investigate but small question: can a rasp pi handle normal home traffic? Netflix, YouTube, gaming etc?

as long as it's just carrying the traffic and shoving it over lokinet, yea. as for gaming, depending on the latency you have with the exit it could work out but it really depends on if you can get sub 300ms rtt.

**Comment by filipesmedeiros** [comment]
> as for gaming, depending on the latency you have with the exit it could work out but it really depends on if you can get sub 300ms rtt.

nice! maybe i could leave gaming out of it and going directly to the isp (or wtv)

that would be awesome, i'll look into this!

**Comment by necro-nemesis** [comment]
> That's amazing! I will investigate but small question: can a rasp pi handle normal home traffic? Netflix, YouTube, gaming etc?

Pi 4 configured as desktop, access point or router handles YouTube np. Someone is running a Minecraft server on Lokinet I'm told is playable. Pi-Apps has both a pi Minecraft installer and Lokinet installer for desktop so it'd be easy to test.
