### ISSUE TITLE
/var/lib/lokinet/router/lokinet.ini (code=dumped, signal=SEGV)

### ISSUE THREAD

**Issue by Stardock2018** [oxen-io/lokinet#1743]
**Describe the bug**
 lokinet-router.service - LokiNET: Anonymous Network layer thingydoo, router
   Loaded: loaded (/lib/systemd/system/lokinet-router.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: core-dump) since Fri 2021-09-17 10:43:55 MDT; 4s ago
  Process: 4944 ExecStart=/usr/bin/lokinet -r /var/lib/lokinet/router/lokinet.ini (code=dumped, signal=SEGV)
 Main PID: 4944 (code=dumped, signal=SEGV)

**Device and Operating system (please complete the following information):**
 - OS: Ubuntu 18.04
 - Lokinet Version number lokinet v0.9.6

**Comment by majestrate** [comment]
`latest` is not a git commit hash

**Comment by jagerman** [comment]
Can you copy the output of: `sudo journalctl -u lokinet-router -n 100`

**Comment by Stardock2018** [comment]
Sep 17 12:30:43 supernode lokinet-router[20700]: [NFO] [lokinet](959) 2021-09-17 18:30:43.953 GMT [+0.001s] llarp/context.cpp:64        lokinet-0.9.6-deb0.9.6-1~ubuntu1804 A Series
Sep 17 12:30:43 supernode lokinet-router[20700]: [NFO] [lokinet](959) 2021-09-17 18:30:43.953 GMT [+0.001s] llarp/context.cpp:65        starting up
Sep 17 12:30:43 supernode lokinet-router[20700]: [NFO] [lokinet](959) 2021-09-17 18:30:43.959 GMT [+0.007s] llarp/rpc/lokid_rpc_client.cpp:60        connecting to lokid via LMQ at i
Sep 17 12:30:43 supernode lokinet-router[20700]: [ERR] [lokinet](959) 2021-09-17 18:30:43.959 GMT [+0.007s] llarp/router_contact.cpp:565        Failed to open "/var/lib/lokinet/rout
Sep 17 12:30:43 supernode lokinet-router[20700]: [NFO] [lokinet](959) 2021-09-17 18:30:43.959 GMT [+0.007s] llarp/router/router.cpp:582        Loaded 3 bootstrap routers
Sep 17 12:30:43 supernode lokinet-router[20700]: [ERR] [lokinet](959) 2021-09-17 18:30:43.960 GMT [+0.008s] daemon/lokinet.cpp:293        Fatal: caught exception while running: serv
Sep 17 12:30:43 supernode lokinet-router[20700]: main thread threw exception: service node enabled but could not find a public IP to bind to; you need to set the public-ip= and publ
Sep 17 12:30:44 supernode systemd[1]: lokinet-router.service: Main process exited, code=dumped, status=11/SEGV
Sep 17 12:30:44 supernode systemd[1]: lokinet-router.service: Failed with result 'core-dump'.
Sep 17 12:30:44 supernode systemd[1]: Failed to start LokiNET: Anonymous Network layer thingydoo, router.
Sep 17 12:30:49 supernode systemd[1]: lokinet-router.service: Service hold-off time over, scheduling restart.
Sep 17 12:30:49 supernode systemd[1]: lokinet-router.service: Scheduled restart job, restart counter is at 2890.
Sep 17 12:30:49 supernode systemd[1]: Stopped LokiNET: Anonymous Network layer thingydoo, router.
Sep 17 12:30:49 supernode systemd[1]: Starting LokiNET: Anonymous Network layer thingydoo, router...
Sep 17 12:30:49 supernode lokinet-router[20730]: [NFO] [lokinet](349) 2021-09-17 18:30:49.200 GMT [+0.001s] daemon/lokinet.cpp:264        Using config file: "/var/lib/lokinet/router
Sep 17 12:30:49 supernode lokinet-router[20730]: [NFO] [lokinet](349) 2021-09-17 18:30:49.202 GMT [+0.003s] llarp/context.cpp:64        lokinet-0.9.6-deb0.9.6-1~ubuntu1804 A Series
Sep 17 12:30:49 supernode lokinet-router[20730]: [NFO] [lokinet](349) 2021-09-17 18:30:49.202 GMT [+0.003s] llarp/context.cpp:65        starting up
Sep 17 12:30:49 supernode lokinet-router[20730]: [NFO] [lokinet](349) 2021-09-17 18:30:49.205 GMT [+0.006s] llarp/rpc/lokid_rpc_client.cpp:60        connecting to lokid via LMQ at i
Sep 17 12:30:49 supernode lokinet-router[20730]: [ERR] [lokinet](349) 2021-09-17 18:30:49.205 GMT [+0.006s] llarp/router_contact.cpp:565        Failed to open "/var/lib/lokinet/rout
Sep 17 12:30:49 supernode lokinet-router[20730]: [NFO] [lokinet](349) 2021-09-17 18:30:49.206 GMT [+0.007s] llarp/router/router.cpp:582        Loaded 3 bootstrap routers
Sep 17 12:30:49 supernode lokinet-router[20730]: [ERR] [lokinet](349) 2021-09-17 18:30:49.206 GMT [+0.007s] daemon/lokinet.cpp:293        Fatal: caught exception while running: serv
Sep 17 12:30:49 supernode lokinet-router[20730]: main thread threw exception: service node enabled but could not find a public IP to bind to; you need to set the public-ip= and publ
Sep 17 12:30:49 supernode systemd[1]: lokinet-router.service: Main process exited, code=dumped, status=11/SEGV
Sep 17 12:30:49 supernode systemd[1]: lokinet-router.service: Failed with result 'core-dump'.
Sep 17 12:30:49 supernode systemd[1]: Failed to start LokiNET: Anonymous Network layer thingydoo, router.
Sep 17 12:30:54 supernode systemd[1]: lokinet-router.service: Service hold-off time over, scheduling restart.
Sep 17 12:30:54 supernode systemd[1]: lokinet-router.service: Scheduled restart job, restart counter is at 2891.
Sep 17 12:30:54 supernode systemd[1]: Stopped LokiNET: Anonymous Network layer thingydoo, router.
Sep 17 12:30:54 supernode systemd[1]: Starting LokiNET: Anonymous Network layer thingydoo, router...
Sep 17 12:30:54 supernode lokinet-router[20790]: [NFO] [lokinet](677) 2021-09-17 18:30:54.450 GMT [+0.001s] daemon/lokinet.cpp:264        Using config file: "/var/lib/lokinet/router
Sep 17 12:30:54 supernode lokinet-router[20790]: [NFO] [lokinet](677) 2021-09-17 18:30:54.451 GMT [+0.002s] llarp/context.cpp:64        lokinet-0.9.6-deb0.9.6-1~ubuntu1804 A Series
Sep 17 12:30:54 supernode lokinet-router[20790]: [NFO] [lokinet](677) 2021-09-17 18:30:54.452 GMT [+0.003s] llarp/context.cpp:65        starting up
Sep 17 12:30:54 supernode lokinet-router[20790]: [NFO] [lokinet](677) 2021-09-17 18:30:54.455 GMT [+0.006s] llarp/rpc/lokid_rpc_client.cpp:60        connecting to lokid via LMQ at i
Sep 17 12:30:54 supernode lokinet-router[20790]: [ERR] [lokinet](677) 2021-09-17 18:30:54.456 GMT [+0.007s] llarp/router_contact.cpp:565        Failed to open "/var/lib/lokinet/rout
Sep 17 12:30:54 supernode lokinet-router[20790]: [NFO] [lokinet](677) 2021-09-17 18:30:54.461 GMT [+0.012s] llarp/router/router.cpp:582        Loaded 3 bootstrap routers
Sep 17 12:30:54 supernode lokinet-router[20790]: [ERR] [lokinet](677) 2021-09-17 18:30:54.461 GMT [+0.012s] daemon/lokinet.cpp:293        Fatal: caught exception while running: serv
Sep 17 12:30:54 supernode lokinet-router[20790]: main thread threw exception: service node enabled but could not find a public IP to bind to; you need to set the public-ip= and publ
Sep 17 12:30:54 supernode systemd[1]: lokinet-router.service: Main process exited, code=dumped, status=11/SEGV
Sep 17 12:30:54 supernode systemd[1]: lokinet-router.service: Failed with result 'core-dump'.
Sep 17 12:30:54 supernode systemd[1]: Failed to start LokiNET: Anonymous Network layer thingydoo, router.
Sep 17 12:30:59 supernode systemd[1]: lokinet-router.service: Service hold-off time over, scheduling restart.
Sep 17 12:30:59 supernode systemd[1]: lokinet-router.service: Scheduled restart job, restart counter is at 2892.
Sep 17 12:30:59 supernode systemd[1]: Stopped LokiNET: Anonymous Network layer thingydoo, router.
Sep 17 12:30:59 supernode systemd[1]: Starting LokiNET: Anonymous Network layer thingydoo, router...
Sep 17 12:30:59 supernode lokinet-router[20811]: [NFO] [lokinet](151) 2021-09-17 18:30:59.702 GMT [+0.003s] daemon/lokinet.cpp:264        Using config file: "/var/lib/lokinet/router
Sep 17 12:30:59 supernode lokinet-router[20811]: [NFO] [lokinet](151) 2021-09-17 18:30:59.703 GMT [+0.004s] llarp/context.cpp:64        lokinet-0.9.6-deb0.9.6-1~ubuntu1804 A Series
Sep 17 12:30:59 supernode lokinet-router[20811]: [NFO] [lokinet](151) 2021-09-17 18:30:59.703 GMT [+0.004s] llarp/context.cpp:65        starting up
Sep 17 12:30:59 supernode lokinet-router[20811]: [NFO] [lokinet](151) 2021-09-17 18:30:59.706 GMT [+0.007s] llarp/rpc/lokid_rpc_client.cpp:60        connecting to lokid via LMQ at i
Sep 17 12:30:59 supernode lokinet-router[20811]: [ERR] [lokinet](151) 2021-09-17 18:30:59.706 GMT [+0.007s] llarp/router_contact.cpp:565        Failed to open "/var/lib/lokinet/rout
Sep 17 12:30:59 supernode lokinet-router[20811]: [NFO] [lokinet](151) 2021-09-17 18:30:59.707 GMT [+0.008s] llarp/router/router.cpp:582        Loaded 3 bootstrap routers
Sep 17 12:30:59 supernode lokinet-router[20811]: [ERR] [lokinet](151) 2021-09-17 18:30:59.708 GMT [+0.009s] daemon/lokinet.cpp:293        Fatal: caught exception while running: serv
Sep 17 12:30:59 supernode lokinet-router[20811]: main thread threw exception: service node enabled but could not find a public IP to bind to; you need to set the public-ip= and publ
Sep 17 12:30:59 supernode systemd[1]: lokinet-router.service: Main process exited, code=dumped, status=11/SEGV
Sep 17 12:30:59 supernode systemd[1]: lokinet-router.service: Failed with result 'core-dump'.
Sep 17 12:30:59 supernode systemd[1]: Failed to start LokiNET: Anonymous Network layer thingydoo, router.
Sep 17 12:31:04 supernode systemd[1]: lokinet-router.service: Service hold-off time over, scheduling restart.
Sep 17 12:31:04 supernode systemd[1]: lokinet-router.service: Scheduled restart job, restart counter is at 2893.
Sep 17 12:31:04 supernode systemd[1]: Stopped LokiNET: Anonymous Network layer thingydoo, router.
Sep 17 12:31:04 supernode systemd[1]: Starting LokiNET: Anonymous Network layer thingydoo, router...
Sep 17 12:31:04 supernode lokinet-router[20837]: [NFO] [lokinet](748) 2021-09-17 18:31:04.952 GMT [+0.001s] daemon/lokinet.cpp:264        Using config file: "/var/lib/lokinet/router
Sep 17 12:31:04 supernode lokinet-router[20837]: [NFO] [lokinet](748) 2021-09-17 18:31:04.953 GMT [+0.002s] llarp/context.cpp:64        lokinet-0.9.6-deb0.9.6-1~ubuntu1804 A Series
Sep 17 12:31:04 supernode lokinet-router[20837]: [NFO] [lokinet](748) 2021-09-17 18:31:04.953 GMT [+0.002s] llarp/context.cpp:65        starting up
Sep 17 12:31:04 supernode lokinet-router[20837]: [NFO] [lokinet](748) 2021-09-17 18:31:04.956 GMT [+0.005s] llarp/rpc/lokid_rpc_client.cpp:60        connecting to lokid via LMQ at i
Sep 17 12:31:04 supernode lokinet-router[20837]: [ERR] [lokinet](748) 2021-09-17 18:31:04.957 GMT [+0.006s] llarp/router_contact.cpp:565        Failed to open "/var/lib/lokinet/rout
Sep 17 12:31:04 supernode lokinet-router[20837]: [NFO] [lokinet](748) 2021-09-17 18:31:04.957 GMT [+0.006s] llarp/router/router.cpp:582        Loaded 3 bootstrap routers
Sep 17 12:31:04 supernode lokinet-router[20837]: [ERR] [lokinet](748) 2021-09-17 18:31:04.958 GMT [+0.007s] daemon/lokinet.cpp:293        Fatal: caught exception while running: serv
Sep 17 12:31:04 supernode lokinet-router[20837]: main thread threw exception: service node enabled but could not find a public IP to bind to; you need to set the public-ip= and public-port= options
Sep 17 12:31:05 supernode systemd[1]: lokinet-router.service: Main process exited, code=dumped, status=11/SEGV
Sep 17 12:31:05 supernode systemd[1]: lokinet-router.service: Failed with result 'core-dump'.
Sep 17 12:31:05 supernode systemd[1]: Failed to start LokiNET: Anonymous Network layer thingydoo, router.
Sep 17 12:31:10 supernode systemd[1]: lokinet-router.service: Service hold-off time over, scheduling restart.
Sep 17 12:31:10 supernode systemd[1]: lokinet-router.service: Scheduled restart job, restart counter is at 2894.
Sep 17 12:31:10 supernode systemd[1]: Stopped LokiNET: Anonymous Network layer thingydoo, router.
Sep 17 12:31:10 supernode systemd[1]: Starting LokiNET: Anonymous Network layer thingydoo, router...
Sep 17 12:31:10 supernode lokinet-router[20871]: [NFO] [lokinet](669) 2021-09-17 18:31:10.199 GMT [+0.004s] daemon/lokinet.cpp:264        Using config file: "/var/lib/lokinet/router/lokinet.ini"
Sep 17 12:31:10 supernode lokinet-router[20871]: [NFO] [lokinet](669) 2021-09-17 18:31:10.204 GMT [+0.009s] llarp/context.cpp:64        lokinet-0.9.6-deb0.9.6-1~ubuntu1804 A Series of Tubes
Sep 17 12:31:10 supernode lokinet-router[20871]: [NFO] [lokinet](669) 2021-09-17 18:31:10.204 GMT [+0.009s] llarp/context.cpp:65        starting up
Sep 17 12:31:10 supernode lokinet-router[20871]: [NFO] [lokinet](669) 2021-09-17 18:31:10.206 GMT [+0.011s] llarp/rpc/lokid_rpc_client.cpp:60        connecting to lokid via LMQ at ipc:///var/lib/loki/lokid.sock
Sep 17 12:31:10 supernode lokinet-router[20871]: [ERR] [lokinet](669) 2021-09-17 18:31:10.206 GMT [+0.011s] llarp/router_contact.cpp:565        Failed to open "/var/lib/lokinet/router/self.signed"
Sep 17 12:31:10 supernode lokinet-router[20871]: [NFO] [lokinet](669) 2021-09-17 18:31:10.206 GMT [+0.011s] llarp/router/router.cpp:582        Loaded 3 bootstrap routers
Sep 17 12:31:10 supernode lokinet-router[20871]: [ERR] [lokinet](669) 2021-09-17 18:31:10.207 GMT [+0.012s] daemon/lokinet.cpp:293        Fatal: caught exception while running: service node enabled but could not find a public IP to bind to; you need to set the public
Sep 17 12:31:10 supernode lokinet-router[20871]: main thread threw exception: service node enabled but could not find a public IP to bind to; you need to set the public-ip= and public-port= options
Sep 17 12:31:10 supernode systemd[1]: lokinet-router.service: Main process exited, code=dumped, status=11/SEGV
Sep 17 12:31:10 supernode systemd[1]: lokinet-router.service: Failed with result 'core-dump'.
Sep 17 12:31:10 supernode systemd[1]: Failed to start LokiNET: Anonymous Network layer thingydoo, router.
Sep 17 12:31:15 supernode systemd[1]: lokinet-router.service: Service hold-off time over, scheduling restart.
Sep 17 12:31:15 supernode systemd[1]: lokinet-router.service: Scheduled restart job, restart counter is at 2895.
Sep 17 12:31:15 supernode systemd[1]: Stopped LokiNET: Anonymous Network layer thingydoo, router.
Sep 17 12:31:15 supernode systemd[1]: Starting LokiNET: Anonymous Network layer thingydoo, router...
Sep 17 12:31:15 supernode lokinet-router[20898]: [NFO] [lokinet](791) 2021-09-17 18:31:15.450 GMT [+0.001s] daemon/lokinet.cpp:264        Using config file: "/var/lib/lokinet/router/lokinet.ini"
Sep 17 12:31:15 supernode lokinet-router[20898]: [NFO] [lokinet](791) 2021-09-17 18:31:15.451 GMT [+0.002s] llarp/context.cpp:64        lokinet-0.9.6-deb0.9.6-1~ubuntu1804 A Series of Tubes
Sep 17 12:31:15 supernode lokinet-router[20898]: [NFO] [lokinet](791) 2021-09-17 18:31:15.451 GMT [+0.002s] llarp/context.cpp:65        starting up
Sep 17 12:31:15 supernode lokinet-router[20898]: [NFO] [lokinet](791) 2021-09-17 18:31:15.455 GMT [+0.006s] llarp/rpc/lokid_rpc_client.cpp:60        connecting to lokid via LMQ at ipc:///var/lib/loki/lokid.sock
Sep 17 12:31:15 supernode lokinet-router[20898]: [ERR] [lokinet](791) 2021-09-17 18:31:15.455 GMT [+0.006s] llarp/router_contact.cpp:565        Failed to open "/var/lib/lokinet/router/self.signed"
Sep 17 12:31:15 supernode lokinet-router[20898]: [NFO] [lokinet](791) 2021-09-17 18:31:15.458 GMT [+0.009s] llarp/router/router.cpp:582        Loaded 3 bootstrap routers
Sep 17 12:31:15 supernode lokinet-router[20898]: [ERR] [lokinet](791) 2021-09-17 18:31:15.458 GMT [+0.009s] daemon/lokinet.cpp:293        Fatal: caught exception while running: service node enabled but could not find a public IP to bind to; you need to set the public
Sep 17 12:31:15 supernode lokinet-router[20898]: main thread threw exception: service node enabled but could not find a public IP to bind to; you need to set the public-ip= and public-port= options
Sep 17 12:31:15 supernode systemd[1]: lokinet-router.service: Main process exited, code=dumped, status=11/SEGV
Sep 17 12:31:15 supernode systemd[1]: lokinet-router.service: Failed with result 'core-dump'.
Sep 17 12:31:15 supernode systemd[1]: Failed to start LokiNET: Anonymous Network layer thingydoo, router.
lines 68-101/101 (END)

**Comment by majestrate** [comment]
the error message is quite clear: `service node enabled but could not find a public IP to bind to; you need to set the public-ip= and public-port= options`
