### ISSUE TITLE
missing liblokinet-util.so when built in shared mode

### ISSUE THREAD

**Issue by cathugger** [oxen-io/lokinet#1745]
**Describe the bug**
`make install` doesnt install liblokinet-util.so when built in shared mode so it fails to start
seems new to 0.9.6 as this used to work with 0.9.5

**To Reproduce**
build stuff as in https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lokinet but 0.9.6

**Screenshots Or Logs**
`/usr/bin/lokinet: error while loading shared libraries: liblokinet-util.so: cannot open shared object file: No such file or directory`

**Device and Operating system (please complete the following information):**
 - OS: arch btw
-  Device: pc
 - Lokinet Version number or Git commit hash: 0.9.6

**Comment by majestrate** [comment]
fixed by https://github.com/oxen-io/lokinet/commit/ed271de7155ce3884ba84be72b3308c6c2b879db
