### ISSUE TITLE
iOS cmake builds only work with Xcode generator

### ISSUE THREAD

**Issue by liilac** [oxen-io/lokinet#176]
TODO: investigate whether this is fixable

Issue: cmake fails if you use `-GNinja` or any generator other than `Xcode`

Sample working cmake command for reference:
`cmake -S /path/to/loki-network -B loki-network-ios-build -DCMAKE_TOOLCHAIN_FILE=/path/to/ios.toolchain.cmake -DIOS_PLATFORM=OS64`

**Comment by liilac** [comment]
@neuroscr @neilsandriesse just pinging as this was relevant to our discussion earlier, might be helpful for reference

**Comment by majestrate** [comment]
this should be fixed now, we use Ninja generator.
