### ISSUE TITLE
raspberry pi - lokinet : Depends: lokinet-bin (= 0.9.6-4~ubuntu2004)

### ISSUE THREAD

**Issue by peepo5** [oxen-io/lokinet#1763]
**Describe the bug**
When installing lokinet on a raspberry pi it gives the following error after adding the repos and running `sudo apt install lokinet`:
```
The following packages have unmet dependencies:
 lokinet : Depends: lokinet-bin (= 0.9.6-4~ubuntu2004) but 0.9.6-3~ubuntu2004 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**To Reproduce**
Unsure.
Install a fresh OS with the specs below and follow the lokinet readme install.

**Screenshots Or Logs**
![image](https://user-images.githubusercontent.com/72892531/136292583-4540bae3-c63e-4142-8d2f-2b193c14c40f.png)

**Device and Operating system (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS aarch64
-  Device: Raspberry Pi 4 Model B Rev 1.2
-  Kernel: 5.4.0-1043-raspi
 - Lokinet Version number or Git commit hash: latest stable

**Comment by jagerman** [comment]
Will be fixed shortly; an update to amd64 got pushed (including the arch=all package) but the debs for arm are still building.

**Comment by peepo5** [comment]
@jagerman it is not fixed yet, any idea when it will be?

**Comment by jagerman** [comment]
> @jagerman it is not fixed yet, any idea when it will be?

It should be fixed since several hours ago.  Did you try refreshing the package list?  (There should be a -5 release now that resolves it).

**Comment by peepo5** [comment]
oh, i only think i tried running apt get install lokinet again. will try.

**Comment by peepo5** [comment]
:+1:

**Comment by Minecon724** [comment]
```
The following packages have unmet dependencies:
 lokinet : Depends: lokinet-bin (= 0.9.10-3~deb11) but 0.9.10-2~deb11 is to be installed
E: Unable to correct problems, you have held broken packages.
```
again

**Comment by jagerman** [comment]
Should be fixed now.
