### ISSUE TITLE
fatal error: charconv: No such file or directory

### ISSUE THREAD

**Issue by sh4m2hwz** [oxen-io/lokinet#1768]
In file included from /path/to/lokinet/llarp/util/logging/logger.hpp:4:0,
                 from /path/to/lokinet/llarp/util/bencode.hpp:6,
                 from /path/to/lokinet/llarp/util/bencode.cpp:1:
/path/to/lokinet/llarp/util/str.hpp:8:10: fatal error: charconv: No such file or directory
 #include <charconv>
          ^~~~~~~~~~
compilation terminated.
In file included from /path/to/lokinet/llarp/util/logging/logger.hpp:4:0,
                 from /path/to/lokinet/llarp/util/fs.cpp:3:
/path/to/lokinet/llarp/util/str.hpp:8:10: fatal error: charconv: No such file or directory
 #include <charconv>
os:
ubuntu 18.04

**Comment by majestrate** [comment]
18.04 is too old, we don't support it as their gcc doesn't have the required features.
