### ISSUE TITLE
Interrupted VPN connection causes IP leak

### ISSUE THREAD

**Issue by mahdi-ln** [oxen-io/lokinet#1785]
**Describe the bug**
after running `lokinet-vpn --up --exit exit.loki` for a few seconds my IP changes. then after a while, It connect to every site with real IP again 

**To Reproduce**
I installed using ~~www.oxen.io~~ www.oxen.rocks website builds. Is that domain belongs to Oxen, too?
```
$ yay -S lokinet-bin        # lokinet-bin uses above site binaries
$ sudo wget -O /var/lib/lokinet/bootstrap.signed https://seed.lokinet.org/lokinet.signed   /
    # because lokinet-bootsrap gives HTTP 0 error 
$ sudo systemctl start lokinet 
$ lokinet-vpn --up --exit exit.loki
```

**Device and Operating system (please complete the following information):**
 - OS: Manjaro 
-  Device:PC
 - Lokinet Version number or Git commit hash: https://oxen.rocks/oxen-io/loki-network/lokinet-linux-amd64-v0.9.7.tar.xz

**Comment by majestrate** [comment]
the static lokinet builds for lokinet should not be used for new installs they are a legacy support thing and they have 2 problems:

* static libssl with no CA certs 
* no sd_notify support

the first causes lokinet-bootstrap to fail
the second causes systemd to kill lokinet if run in a `type=notify` systemd unit, which will cause it to constantly restart.

both the lokinet and lokinet-bin packages on the aur are packaged wrong and it's not a surprise as we're talking about arch linux after all.

**Comment by mahdi-ln** [comment]
I'm not going to leave Arch Linux because I want to use this https://github.com/kpcyrd/pacman-bintrans
P.S. It can assures other Lokinet users too

**Comment by majestrate** [comment]
we are working on fixing this issue with the aur pacakges, see https://github.com/oxen-io/lokinet/issues/1783#issuecomment-952211723
