### ISSUE TITLE
Official Lokinet windows binary missing from lokinet.org; I need the lokinet binary from lokinet.org to use lokinet exit nodes.

### ISSUE THREAD

**Issue by Destroyinator69420** [oxen-io/lokinet#1788]
**Describe the bug**
The Lokinet download for windows is missing from lokinet.org. It returns a 404. The binary from github does not have working exit nodes, despite being built from the same code. The only difference in the two that I can notice is that the lokinet.org binary is signed, and the github.com/oxen-io/lokinet binary is not.

**To Reproduce**
Use the github binary for lokinet win32, the exit node does not work.
Use the lokinet.org win32 binary, the exit node works. 
(Both steps use the exit.loki node)\

**Device and Operating system (please complete the following information):**
 - OS: Windows 10 21H1
-  Device: Lenovo c940
 - Lokinet Version number or Git commit hash: 0.9.7 (github binary)

**Comment by majestrate** [comment]
we are waiting on obtaining new signing key for windows, cc @KeeJef

**Comment by KeeJef** [comment]
This is fixed now, Lokinet site was directing towards non existing file, signing should not effect functionality once installed, just gives some extra warnings. If Exits are not working then that could be a different issue

**Comment by majestrate** [comment]
they are now out on lokinet.org as of the v0.9.10 release
