### ISSUE TITLE
Ubuntu18.04 failure to compile

### ISSUE THREAD

**Issue by hadesjaky** [oxen-io/lokinet#1789]
**Describe the bug**
[ 19%] Built target zmq_external
[ 28%] Built target ngtcp2
[ 38%] Built target lokinet-cryptography
[ 42%] Built target cpr
[ 44%] Built target oxenmq
[ 50%] Built target lokinet-util
[ 53%] Built target lokinet-platform
[ 87%] Built target liblokinet
[ 87%] Built target lokinet
[ 87%] Built target lokinet-vpn
[ 88%] Built target lokinet-bootstrap
[ 89%] Built target lokinet-shared
[ 89%] Linking CXX executable testAll
lto1: internal compiler error: in add_symbol_to_partition_1, at lto/lto-partition.c:155
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
test/CMakeFiles/testAll.dir/build.make:1043: recipe for target 'test/testAll' failed
make[2]: *** [test/testAll] Error 1
CMakeFiles/Makefile2:2226: recipe for target 'test/CMakeFiles/testAll.dir/all' failed
make[1]: *** [test/CMakeFiles/testAll.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Screenshots Or Logs**
Ubuntu18.04

gcc-8 (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

** Lokinet Version number or Git commit hash **:
commit： fd81ee76af983e17acfdd531f4210806e8575fb1 (HEAD -> dev, origin/dev, origin/HEAD)

**Comment by jagerman** [comment]
LTO makes binaries smaller, but gcc's implementation is notoriously buggy.  Try invoking cmake with `-DWITH_LTO=OFF` to disable it; binaries will be a bit bigger but you won't have the crash (and the build overall time will be faster).

**Comment by hadesjaky** [comment]
> LTO makes binaries smaller, but gcc's implementation is notoriously buggy. Try invoking cmake with `-DWITH_LTO=OFF` to disable it; binaries will be a bit bigger but you won't have the crash (and the build overall time will be faster).

Thank you
