### ISSUE TITLE
what():  Address already in use after RPC server bount to tcp://localhost:1190

### ISSUE THREAD

**Issue by nosfirlabs** [oxen-io/lokinet#1792]
**Describe the bug**
After installing lokinet using the apt manager on ubuntu and running "lokinet" in a terminal, i get the following error.

**To Reproduce**
curl -s https://deb.imaginary.stream/public.gpg | sudo apt-key add -
echo "deb https://deb.imaginary.stream $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/imaginary.stream.list
sudo apt update
sudo apt install lokinet

lokinet

**Screenshots Or Logs**
https://imgur.com/Q7YLykn

**Device and Operating system (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
-  Device: PC
 - Lokinet Version number: v0.9.7

**Comment by majestrate** [comment]
lokinet runs as a system service in the background and it is enabled by default. you do not have to run it in foreground.
