### ISSUE TITLE
Don't work on ubuntu 21.04 and 21.10 "terminate called after throwing an instance of 'zmq::error_t'"

### ISSUE THREAD

**Issue by ghost** [oxen-io/lokinet#1793]
When i start lokinet: 

me@me:~/ lokinet
[NFO] [lokinet](401) 2021-10-31 07:24:52.307 GMT [+0.002s] ../daemon/lokinet.cpp:238	Using config file: "/home/adam/.lokinet/lokinet.ini"
[NFO] [lokinet](401) 2021-10-31 07:24:52.307 GMT [+0.002s] ../llarp/context.cpp:64	lokinet-0.9.7-deb0.9.7-2~ubuntu2104 A Series of Tubes
[NFO] [lokinet](401) 2021-10-31 07:24:52.307 GMT [+0.002s] ../llarp/context.cpp:65	starting up
[NFO] [lokinet](401) 2021-10-31 07:24:52.308 GMT [+0.003s] ../llarp/router/router.cpp:1113	Bound RPC server to tcp://127.0.0.1:1190
terminate called after throwing an instance of 'zmq::error_t'
  what():  Address already in use

================================================
lokinet is work as system service:
================================================
me@me:~$ systemctl status lokinet
● lokinet.service - LokiNET: Anonymous Network layer thingydoo, client
     Loaded: loaded (/lib/systemd/system/lokinet.service; enabled; vendor prese>
     Active: active (running) since Sun 2021-10-31 09:55:47 MSK; 9min ago
   Main PID: 1718 (lokinet)
     Status: "v0.9.7 client | known/connected: 1743/4 | path success:  [default>
      Tasks: 14 (limit: 8707)
     Memory: 27.8M
        CPU: 4.924s
     CGroup: /system.slice/lokinet.service
             └─1718 /usr/bin/lokinet /var/lib/lokinet/lokinet.ini

But why, then my ip stays the same as before the installation of the lokinet and the .loki domains do not work ?

I am currently using ubuntu 21.10 but in 21.04 it was the same.

**Comment by majestrate** [comment]
~~duplicate of #1792~~

**Comment by majestrate** [comment]
looks like dns is not being set right (again). to change io you need to tell it to use an exit.

**Comment by ghost** [comment]
> looks like dns is not being set right (again). to change io you need to tell it to use an exit.

and how can i do it?

**Comment by majestrate** [comment]
for dns, make sure `/etc/resolv.conf` contains `nameserver 127.3.2.1` as the first entry
for exit node add this to `/var/lib/lokinet/conf.d/00-exit.ini` (create the parent directory as needed and create the file if not present).

```
[network]
exit-node=exit.loki
```

then restart lokinet
