### ISSUE TITLE
DNS Leaks when using Exit Node

### ISSUE THREAD

**Issue by 144** [oxen-io/lokinet#1794]
**Describe the bug**
Real client IP is leaking with DNS requests while using Exit Node.

**To Reproduce**
Launch Lokinet GUI -> Set Exit Node(I've used exit.loki) -> Check DNS leaks(for example on ipleak.net)

**Device and Operating system:**
 - OS: Windows 21H1
-  Device: PC
 - Lokinet Version: 0.9.7

**Comment by majestrate** [comment]
we know, we have a draft PR being worked on that isn't done yet to fix this. there is SO MUCH other stuff to do but it is currently priority 1 in lokinet. see #1740

**Comment by 144** [comment]
> 
> 
> we know, we have a draft PR being worked on that isn't done yet to fix this. there is SO MUCH other stuff to do but it is currently priority 1 in lokinet. see #1740

All right, thank you very much for replying :)
I'm glad to see it on the list and of course I understand there are more important things than that, I just didn't see it earlier, I'm testing Lokinet on daily basis now and I love it.
Keep up the good work!
