### ISSUE TITLE
lokinet-bootstrap not working on Arch Linux

### ISSUE THREAD

**Issue by jahway603** [oxen-io/lokinet#1798]
**Describe the bug**
lokinet-bootstrap provides the following error when using it:
```
$ lokinet-bootstrap 
fetching https://seed.lokinet.org/lokinet.signed
failed to fetch 'https://seed.lokinet.org/lokinet.signed' HTTP 0
```

**To Reproduce**
1. Download lokinet-linux-amd64-v0.9.7.tar.xz binary release from [here](https://oxen.rocks/oxen-io/loki-network/)
2. Unextract it.
3. Run lokinet-bootstrap
4. Get exact error message above.

**Screenshots Or Logs**
This happens to myself and [these two other people](https://aur.archlinux.org/packages/lokinet-bin/#comment-832917) when trying to use lokinet-bootstrap

**Device and Operating system (please complete the following information):**
 - OS: Arch Linux
-  Device: PC
 - Lokinet Version number or Git commit hash: 0.9.7

**Comment by necro-nemesis** [comment]
You need to specify mainnet `lokinet-bootstrap mainnet /$USER/.lokinet/bootstrap.signed` 

You don't build lokinet bootstrap `-DWITH_BOOTSTRAP=OFF`. Then you can just copy it over from the contrib folder to wherever you are creating .lokinet folder (probably under your user). 
https://github.com/oxen-io/lokinet/tree/stable/contrib/bootstrap
mainnet.signed > .lokinet/bootstrap.signed.

**Comment by necro-nemesis** [comment]
The Arch community should release control over their builds to the Lokinet devs before they are unwilling to supporting it (may already be too late). This sort of instruction shouldn't be required.

**Comment by majestrate** [comment]
the static linux ci builds are not for lokinet clients, they are for service nodes using a super old deprecated setup.
