### ISSUE TITLE
Q: Why should i trust lokinet with my privacy?

### ISSUE THREAD

**Issue by Kreyren** [oxen-io/lokinet#1824]
1. Even though i have 14 years of experience with Computer Science I don't feel qualified to review the code and notice any possible issues for adaptation of my threat model

2. I am unable to hire any qualified expert who is able to process the code confidently

Those who tried were concerned about:
a) The blockchain aspect of keeping the traffic indefinetly across multiple blockchain members with some concerned about this being a scheme to sell user data via blockchain due to that high freeze requirements to run a relay (iirc 2500 EUR per relay in OXEN crypto)
b) loki's ability to use just 1 relay which seems to defeat the multi-layer encryption?
c) Security and privacy oriented project using discord as their primary community chat?
d) Unclear business plan to fund the project
 
3. +-7 months ago I was told that lokinet is undergoing an independent security review, but the findings were never published?

What can i do to understand the issues so that i can adapt my threat model and use loki comfortably?

**Comment by majestrate** [comment]
> The blockchain aspect of keeping the traffic indefinetly across multiple blockchain members with some concerned about this being a scheme to sell user data via blockchain due to that high freeze requirements to run a relay (iirc 2500 EUR per relay in OXEN crypto)

Lokinet always has supported stakeless relays, there has never been enough interest to bootstrap an opennet despite this. I consider the gripes about the lack of an opennet existing despite it being fully supported to be anecdotal evidence of altruistic models being inferior.

> loki's ability to use just 1 relay which seems to defeat the multi-layer encryption?

minimum hops is 2, 1 hops never worked well enough to justify enabling it. default is 4 hops.

> Security and privacy oriented project using discord as their primary community chat?

no one i know of in lokinet uses discord, we have/had an inband irc network at irc.probably.loki i forget if it's still up. at the moment most community chatter is via SOGS. i genuinely despise discord with a passion.

>Unclear business plan to fund the project.

the current idea is to use oxen governance block reward. that is actually not the initial idea for funding, in the very beginning before oxen i planned on having opennet + vpn exit broker pay service. initially there was no business plan to fund the project, then oxen offered a better one.

>+-7 months ago I was told that lokinet is undergoing an independent security review, but the findings were never published?

that was session, not lokinet, the reports of that aduit were posted publicly. I would like a lokinet audit myself.

>What can i do to understand the issues so that i can adapt my threat model and use loki comfortably?

most of these talking points seem to come as a game of the internet hearsay telephone game. when in doubt ask questions here. I'll do my best to answer them.

**Comment by majestrate** [comment]
this is also probably better suited as a discussion, i'll move this there as this is not a bug report.
