### ISSUE TITLE
could not add exit

### ISSUE THREAD

**Issue by nerd36** [oxen-io/lokinet#1850]
```
$ lokinet-vpn --up --exit exit.loki
could not add exit
$ lokinet-vpn --up --exit exit-arda.loki
could not add exit
$ lokinet-vpn --up --exit xite.loki 
could not add exit
$ lokinet-vpn --up --exit euroexit.loki
we could not find an exit with that name
```

**Device and Operating system (please complete the following information):**
 - OS: EndeavorOS
-  Device: PC
 - Lokinet Version: makepkg branch (vv0.9.8_3b0d3f235_3b0d3f235-1)

**Comment by majestrate** [comment]
uptime of lokinet would be useful here. also some logs from systemd.

**Comment by nerd36** [comment]
If I run `lokinet-vpn --up` too soon usually error is `we could not find an exit with that name`

[journalctl.txt](https://github.com/oxen-io/lokinet/files/7997119/journalctl.txt)

**Comment by nerd36** [comment]
I can access loki sites

**Comment by mahdi-ln** [comment]
This problem occurs in Arch based Linux. I have same problem

**Comment by mahdi-ln** [comment]
He has sent [journalctl.txt](https://github.com/oxen-io/lokinet/files/9471032/journalctl.txt) but `more into needed` tag is not removed.
I can connect to loki websites, the problem is lokinet-vpn
