### ISSUE TITLE
install: cannot stat 'LICENSE.txt': No such file or directory

### ISSUE THREAD

**Issue by nerd36** [oxen-io/lokinet#1855]
**Describe the bug**
get `install: cannot stat 'LICENSE.txt': No such file or directory` error when try `makepkg`

**To Reproduce**
$ git clone --branch makepkg https://github.com/oxen-io/lokinet.git
$ cd ./lokinet/contrib/archlinux/
$ makepkg 
**Screenshots Or Logs**
![image](https://user-images.githubusercontent.com/89322511/153718324-768012c5-1569-45da-9b5d-2c9eb5303efa.png)

**Device and Operating system (please complete the following information):**
 - OS: Archlinux 
 - Lokinet Version number or Git commit hash: b87ef5a

**Comment by jagerman** [comment]
I've pushed a fix to the makepkg branch that should fix that.
