### ISSUE TITLE
lokinet does not clean up route exceptions for edge connections.

### ISSUE THREAD

**Issue by majestrate** [oxen-io/lokinet#1885]
**Describe the bug**

Sometimes Lokinet does not clean up route exceptions for edge connections.

**To Reproduce**

On low quality wifi, the number of exceptions to the routing table grows and older entries are not removed.

**Screenshots Or Logs**
N/A

**Device and Operating system (please complete the following information):**
 - OS: Linux
 - Device: Laptop
 - Lokinet Version number or Git commit hash: dev branch

**Comment by jagerman** [comment]
I believe this issue is either no longer occurring, or is addressed in #1969 (at least, while testing that PR, I've observed routes getting removed).  This likely needs confirmation before closing.
