### ISSUE TITLE
Add Ed25519 pubkey in oxend ping

### ISSUE THREAD

**Issue by jagerman** [oxen-io/lokinet#1892]
A few times someone has restarted their oxend *without* restarting lokinet and storage server, but both of those only get the service node private keys at startup, and so if you change keys, it is quite easy to end up with Lokinet & Storage server running with the wrong keys.

The problem is that this isn't easy to notice because oxend keeps sending pings, and only several hours later (once storage and/or lokinet checks fail) does this result in a decommission on the network.

I'd like to fix it by adding the service node ed25519 pubkey into the ping to oxend, so that oxend can verify and, if wrong, reject the ping.  This, in turn, will make it stop sending proofs, which will usually get noticed quickly by an admin -- and if they check oxend-node logs, they will see prominent errors about lokinet or SS pings having the wrong pubkey.

**Comment by majestrate** [comment]
easy to do
