### ISSUE TITLE
Request: Provide docker container

### ISSUE THREAD

**Issue by Kreyren** [oxen-io/lokinet#1921]
Currently the average entry in lokinet is:
1. Figure out how to package it for your distro
2. Figure out how to configure it to provide SOCKS5 proxy
3. Use it

Which is terrible for new users thus proposing to provide a docker container so that it's just copy pasting a command and using the provided port

**Comment by majestrate** [comment]
you are using lokinet wrong. we do have docker containers but i am not sure you will have any luck here as docker is worse not better. https://github.com/oxen-io/oxen-docker
