### ISSUE TITLE
Binding to wrong IP

### ISSUE THREAD

**Issue by jagerman** [oxen-io/lokinet#1929]
On a service node I have the following config (irrelevant bits of config snipped):
```
[router]
public-ip=149.56.165.112
public-port=10909
[bind]
0.0.0.0=10909
```
but the lokinet's open udp ports end up as:
```
udp        0      0 51.79.20.22:10909       0.0.0.0:*                           1138933/lokinet     
udp        0      0 127.109.0.0:53          0.0.0.0:*                           1138933/lokinet     
udp        0      0 149.56.165.112:41937    0.0.0.0:*                           1138933/lokinet     
```
but this isn't exhibiting the right behaviour: the *output* IP is correctly bound to the public-ip, but the inbound IP looks like it is using the first IP listed on the interface rather than `public-ip`.

The intended behaviour here was to fail in such a case -- i.e. I have more than one IP, and didn't specify one in the `[bind]` section, but it isn't failing: lokinet is starting and apparently just using the first address on the interface.  (The result is an unreachable lokinet, because 149.56.165.112 is the default source IP, but that doesn't work right when we reply to something that we received on 51.x).

I think we need to split up this configuration better, and make the behaviour a little more obvious:

- add new options `incoming=1.2.3.4:1090` and `outgoing=5.6.7.8:1099` options to the `[bind]` section, and make this the only non-deprecated way to specify IPs.  We should probably allow `incoming=:1090` as an alias for `0.0.0.0:1090`
- we likely need to allow multiple `incoming` addresses, probably not `outgoing`.
- for future use, we'll likely want some other keys here (e.g. `quic-in=`, `quic-out=`).
- if you bind to IP 0.0.0.0 (either with the new, or the deprecated, interface, or using a new `:1090` value) then:
  - if we have a `public-ip` given in the `[router]` section and that IP exists on the system, bind to it for both incoming/outgoing IPs.
  - otherwise go looking for a unique public IP and, if we find one (and only one), bind to that.
  - if we find more than one public IP (or no public IP), die with a message that you need to list a specific IP in the `[bind]` section.
- deprecate specifying interface names.  They are non-portable across machines, and also don't uniquely identify an IP (i.e. one interface can have multiple IPs).

**Comment by jagerman** [comment]
Never mind, I had the options wrong.

**Comment by jagerman** [comment]
If I set up a router with:
```ini
[bind] 
inbound=:10706 
```
or `inbound=0.0.0.0:10706` then startup fails with:
```
Jul 21 13:56:50 charolais lokinet[977807]: [2022-07-21 13:56:50] [+0.002s] [:error|daemon/lokinet.cpp:267] failed to set up lokinet: no public ip provided for inbound socket, is lokinet already running? 🤔
```

But those options should be triggering the look-for-a-public-ip behaviour.  (This box has only one public ip, and it finds it fine if I don't try to override the port).

**Comment by majestrate** [comment]
can i get the list of interfaces and addresses on that box?
