### ISSUE TITLE
No connection on lokinet, lokinet-gui after wifi reconnection

### ISSUE THREAD

**Issue by Sygiclogic** [oxen-io/lokinet#1932]
**Describe the bug**
When using lokinet and suddenly your WiFi connection drops , lokinet will not continue to work
To solve this this you need to manually restart lokinet : sudo systemctl restart lokinet

**To Reproduce**
Start lokinet, use exit node, go to your network manager disable and enable your internet connection

**Device and Operating system (please complete the following information):**
 - OS: linux ubuntu
-  Device: laptop/pc
 - Lokinet Version number or Git commit hash:/all versions including gui

**Comment by majestrate** [comment]
try #1933

**Comment by Destroyinator69420** [comment]
I have a very similar problem. I run a customized version of windows using Winearo Tweaker. I do not think that has anything to do with it however. I attached a backup of my tweaks to help you in the form of a .ini file for Winearo Tweaker.
[Winaero Tweaker_2022_06_20.zip](https://github.com/oxen-io/lokinet/files/8945863/Winaero.Tweaker_2022_06_20.zip)

**Comment by jagerman** [comment]
We have reason to believe this issue is fixed in the upcoming 0.9.10 release (which has several changes and fixes around how we detect interfaces and interface changes), so I am closing this issue for now.

If the 0.9.10 release, once available, doesn't solve this then please reopen.
