### ISSUE TITLE
Error installing on Arch Linux

### ISSUE THREAD

**Issue by farzin-az** [oxen-io/lokinet#1934]
Hello,
I followed the instructions on  https://wiki.oxen.io/wiki/Main_Page#Arch_Linux to install lokinet on my newly updated arch system. Compiling happened with success but when I wanted to install the package with "sudo pacman -U lokinet" I ran into this error:
>loading packages...
error: could not open file lokinet: Error reading fd 7
error: 'lokinet': cannot open package file

This is the log I got from running the command above with --debug option:
>debug: pacman v6.0.1 - libalpm v13.0.1
debug: config: attempting to read file /etc/pacman.conf
debug: config: new section 'options'
debug: config: HoldPkg: pacman
debug: config: HoldPkg: glibc
debug: config: Architecture: auto
debug: config: arch: x86_64
debug: config: chomp
debug: config: SigLevel: Required
debug: config: SigLevel: DatabaseOptional
debug: config: LocalFileSigLevel: Optional
debug: config: new section 'core'
debug: config file /etc/pacman.conf, line 77: including /etc/pacman.d/mirrorlist
debug: config: new section 'extra'
debug: config file /etc/pacman.conf, line 80: including /etc/pacman.d/mirrorlist
debug: config: new section 'community'
debug: config file /etc/pacman.conf, line 86: including /etc/pacman.d/mirrorlist
debug: config: finished parsing /etc/pacman.conf
debug: setup_libalpm called
debug: option 'logfile' = /var/log/pacman.log
debug: option 'gpgdir' = /etc/pacman.d/gnupg/
debug: option 'hookdir' = /etc/pacman.d/hooks/
debug: option 'cachedir' = /var/cache/pacman/pkg/
debug: registering sync database 'core'
debug: database path for tree core set to /var/lib/pacman/sync/core.db
debug: "/var/lib/pacman/sync/core.db.sig" is not readable: No such file or directory
debug: sig path /var/lib/pacman/sync/core.db.sig could not be opened
debug: got error 43 at _alpm_gpgme_checksig (../lib/libalpm/signing.c: 599) : missing PGP signature
debug: missing optional signature
debug: setting usage of 15 for core repository
debug: adding new server URL to database 'core': http://mirror.hostiran.ir/archlinux/core/os/x86_64
debug: adding new server URL to database 'core': https://mirror.hostiran.ir/archlinux/core/os/x86_64
debug: adding new server URL to database 'core': http://mirror.bardia.tech/archlinux/core/os/x86_64
debug: adding new server URL to database 'core': https://mirror.bardia.tech/archlinux/core/os/x86_64
debug: adding new server URL to database 'core': http://mirror.arvancloud.com/archlinux/core/os/x86_64
debug: adding new server URL to database 'core': https://mirror.arvancloud.com/archlinux/core/os/x86_64
debug: registering sync database 'extra'
debug: database path for tree extra set to /var/lib/pacman/sync/extra.db
debug: "/var/lib/pacman/sync/extra.db.sig" is not readable: No such file or directory
debug: sig path /var/lib/pacman/sync/extra.db.sig could not be opened
debug: got error 43 at _alpm_gpgme_checksig (../lib/libalpm/signing.c: 599) : missing PGP signature
debug: missing optional signature
debug: setting usage of 15 for extra repository
debug: adding new server URL to database 'extra': http://mirror.hostiran.ir/archlinux/extra/os/x86_64
debug: adding new server URL to database 'extra': https://mirror.hostiran.ir/archlinux/extra/os/x86_64
debug: adding new server URL to database 'extra': http://mirror.bardia.tech/archlinux/extra/os/x86_64
debug: adding new server URL to database 'extra': https://mirror.bardia.tech/archlinux/extra/os/x86_64
debug: adding new server URL to database 'extra': http://mirror.arvancloud.com/archlinux/extra/os/x86_64
debug: adding new server URL to database 'extra': https://mirror.arvancloud.com/archlinux/extra/os/x86_64
debug: registering sync database 'community'
debug: database path for tree community set to /var/lib/pacman/sync/community.db
debug: "/var/lib/pacman/sync/community.db.sig" is not readable: No such file or directory
debug: sig path /var/lib/pacman/sync/community.db.sig could not be opened
debug: got error 43 at _alpm_gpgme_checksig (../lib/libalpm/signing.c: 599) : missing PGP signature
debug: missing optional signature
debug: setting usage of 15 for community repository
debug: adding new server URL to database 'community': http://mirror.hostiran.ir/archlinux/community/os/x86_64
debug: adding new server URL to database 'community': https://mirror.hostiran.ir/archlinux/community/os/x86_64
debug: adding new server URL to database 'community': http://mirror.bardia.tech/archlinux/community/os/x86_64
debug: adding new server URL to database 'community': https://mirror.bardia.tech/archlinux/community/os/x86_64
debug: adding new server URL to database 'community': http://mirror.arvancloud.com/archlinux/community/os/x86_64
debug: adding new server URL to database 'community': https://mirror.arvancloud.com/archlinux/community/os/x86_64
loading packages...
debug: "lokinet.sig" is not readable: No such file or directory
debug: "lokinet.sig" is not readable: No such file or directory
debug: sig data: <from .sig>
debug: "lokinet.sig" is not readable: No such file or directory
debug: sig path lokinet.sig could not be opened
debug: got error 43 at _alpm_gpgme_checksig (../lib/libalpm/signing.c: 599) : missing PGP signature
debug: missing optional signature
debug: opening archive lokinet
error: could not open file lokinet: Error reading fd 7
debug: returning error 39 from _alpm_open_archive (../lib/libalpm/util.c: 283) : cannot open package file
error: 'lokinet': cannot open package file
debug: unregistering database 'local'
debug: unregistering database 'core'
debug: unregistering database 'extra'
debug: unregistering database 'community'

**Comment by majestrate** [comment]
we do not have arch linux packages right now. likely not for a bit too.

**Comment by majestrate** [comment]
see https://github.com/oxen-io/lokinet/discussions/1823

**Comment by farzin-az** [comment]
I managed to install lokinet on my arch system with [this package](https://raw.githubusercontent.com/oxen-io/lokinet/makepkg/contrib/archlinux/PKGBUILD) mentioned in the main github page of lokinet project. It works fine!
