### ISSUE TITLE
RPM patch requirements

### ISSUE THREAD

**Issue by necro-nemesis** [oxen-io/lokinet#1939]
RPMs for all distros are patching cmake/Version.cmake but latest changes require an update to the patch. Additionally some RPMs were experiencing issues with using port 53 which were patched with default-dns.patch. I began to work on revised patches see:  

https://github.com/necro-nemesis/lokinet/blob/rpm/patch/SOURCES/default-dns.patch

for updating default-dns.patch but am at a loss as to the requirements now needed to patch the current version of Version.cmake appropriately to build with the recent changes.

**Comment by jagerman** [comment]
The default dns patch can be dropped entirely with #1969 -- the default on linux for 0.9.10 is to listen on both a high localhost port for systemd (to work around the systemd bug identified in #1887, which is the same bug affecting Fedora), *and* on 127.3.2.1:53 for anything else (e.g. command-line tools, other DNS proxies).

**Comment by necro-nemesis** [comment]
This is easily achieved through removal of the patch from the SPEC file for Fedora distros that use systemd-resolved. CentOS and openSUSE did not previously apply this particular patch as they do not use systemd-resolved by default. I will update the SPEC file when stable branch is bumped and I am able to merge it.

Do you wish to continue to have RPMs built on separate branches? If so I believe F36 required a rebase on the upstream branch.
