### ISSUE TITLE
Route Poker does not poke routes, sometimes.

### ISSUE THREAD

**Issue by majestrate** [oxen-io/lokinet#1940]
**Describe the bug**
On early start up sometimes lokinet does not poke route specs for routing default route over lokinet vpn interface.

**To Reproduce**

* enable exit-node usage in lokinet client
* boot computer with lokinet enabled
* on wifi networks it is more likely that lokinet does not poke route specs for exit usage

**Screenshots Or Logs**
If applicable, add screenshots or log files to help explain your problem.

https://github.com/NixOS/nixpkgs/pull/175335#issuecomment-1160353103

**Device and Operating system (please complete the following information):**
 - OS: nixos 
 -  Device: desktop / laptop
 - Lokinet Version number or Git commit hash: 0.9.9 tag

**Comment by jagerman** [comment]
Possibly addressed in #1969 ?

**Comment by majestrate** [comment]
probably. will verify before tag.
