### ISSUE TITLE
0.97 crashed

### ISSUE THREAD

**Issue by sakurayz** [oxen-io/lokinet#1952]
Faulting application name: lokinet-gui.exe, version: 0.8.0.0, time stamp: 0x60b78e95
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000000
Faulting process id: 0x2e0
Faulting application start time: 0x01d897a33ea8e0c9
Faulting application path: C:\Program Files\Lokinet\share\gui\lokinet-gui.exe
Faulting module path: unknown
Report Id: 27c4a1f2-f80b-4879-a825-d050541611a8
Faulting package full name: 
Faulting package-relative application ID:

**Comment by majestrate** [comment]
wait for the 0.9.10 tag for lokinet on windows please.
