### ISSUE TITLE
Problem Lokinet without systemd

### ISSUE THREAD

**Issue by carabistouflette** [oxen-io/lokinet#1977]
**Describe the bug**
Lokinet isn't working on none systemd system. As it's a privacy related program i think it should be better to add compatibility to well known init system (openrc, runit, s6 and dinit). Systemd is known to have security problem and not really privacy friendly.

**Screenshots Or Logs**
![Screenshot_20220817_232435](https://user-images.githubusercontent.com/75278340/185246620-545c66bf-40f2-4197-80b7-530c37ec2e54.png)

**Device and Operating system (please complete the following information):**
 - OS: Artix linux - runit
-  Device: laptop (lenovo 15ACH6H)
 - Lokinet Version number or Git commit hash: lokinet-0.9.9-94a0b8e

**Comment by majestrate** [comment]
>Lokinet isn't working on none systemd system. 

the error in your screenshot has nothing to do with systemd, it is failing to bind on `127.3.2.1:53` for the dns socket, this is likely because you did not setcap the lokinet binary, we have an option to setcap it properly from the install target from cmake.

>i think it should be better to add compatibility to well known init system

patches welcome. lots of people complain we "dont support" their favorite init, this is an issue with the packaging and system layer. the only thing that needs to be supported wrt an init is ever only systemd and that integration is very useful most of the time, but also optional.

**Comment by carabistouflette** [comment]
I've already done the command
![Screenshot_20220817_234451](https://user-images.githubusercontent.com/75278340/185248756-d7b7a526-f721-48d3-a0ff-153fa7e6da83.png)
That's why i was thinking of systemd

**Comment by carabistouflette** [comment]
![image](https://user-images.githubusercontent.com/75278340/185249148-d382d7a2-43ab-41f2-8de5-b57c724122c4.png)

**Comment by majestrate** [comment]
> I've already done the command ![Screenshot_20220817_234451](https://user-images.githubusercontent.com/75278340/185248756-d7b7a526-f721-48d3-a0ff-153fa7e6da83.png) That's why i was thinking of systemd

i do not see how this could be the fault of systemd, do you have any other reasons to think it is? to me it just looks like something is already bound to the udp port it wants to use.

**Comment by carabistouflette** [comment]
No now i know it's not related to systemd (i was thinking about it because there was a message about systemd-resolved).
But i don't know how to fix the error, i've done the setcap command but nothing changed.

**Comment by majestrate** [comment]
> No now i know it's not related to systemd (i was thinking about it because there was a message about systemd-resolved). But i don't know how to fix the error, i've done the setcap command but nothing changed.

try looking for things on your system that are bound to `udp/53` that may interfere with binding on `127.3.2.1:53`.

I don't know what the issue would be on our side. closing unless there is something that is brought up and we can reopen it.
