### ISSUE TITLE
error while loading shared libraries: libspdlog.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mahdi-ln** [oxen-io/lokinet#1980]
```
$ lokinet -g
lokinet: error while loading shared libraries: libspdlog.so.1: cannot open shared object file: No such file or directory
```

**Device and Operating system (please complete the following information):**
 - OS: Arch Linux 
-  Device: PC
 - Lokinet Version number or Git commit hash: branch `makepkg` commit 16d7307 (using `makepkg`)

**Comment by majestrate** [comment]
`makepkg` branch rebased and added https://github.com/oxen-io/lokinet/commit/de5a35584a8add21e1a6daa1deeb91529c16d832 which should address it. let me know if it works. i am testing it now.

**Comment by majestrate** [comment]
36ffdf4b9 was pushed again, still testing...

**Comment by mahdi-ln** [comment]
My PC is old (and therefore safer). It is still building the new package. But this would be next error:

![image](https://user-images.githubusercontent.com/27496531/187076990-ead89a60-3ff7-489b-a45e-1d41ec69684d.png)

**Comment by majestrate** [comment]
~~suqashed it all into 9b7257fa173d00afe38f6ffd4b1e07fc2238bc03 and it seems to fix it.~~

squashed again to: e6e88a28fb98f73c2c5134d8126f82ecd3cef92a

**Comment by mahdi-ln** [comment]
I was wrong. No error happened during v0.9.10 installation
