### ISSUE TITLE
No Windows Binaries

### ISSUE THREAD

**Issue by TogoorooDev** [oxen-io/lokinet#1981]
According to the docs there should be windows binaries on lokinet.org and on the github release page, however there aren't actually any. Is this an accident or was windows support dropped?

**Comment by Ashthetik** [comment]
They said in the latest release here:
https://github.com/oxen-io/lokinet/discussions/1928#discussioncomment-2980969

**Comment by majestrate** [comment]
the next tag is [v0.9.10](https://github.com/oxen-io/lokinet/milestone/8) and the plan is to have the fixes needed for a proper working windows (see #1969) included in it
