### ISSUE TITLE
No clear option to not connect on boot under Linux

### ISSUE THREAD

**Issue by iHnR** [oxen-io/lokinet#2010]
I installed the lokinet-gui over apt on Ubuntu. 

I noticed that it always connects automatically on boot (confirmed by checking ip). 

There is no obvious way to disable this behaviour in the app other than disabling manually each time. There is also nothing connected to Lokinet in startup apps.

I assume I'm missing some knowhow on how to do this properly but also I think it should be easier to configure?

**Comment by majestrate** [comment]
lokinet-gui is a graphical tool for controlling the lokinet service. this gui depends on the 
 lokinet package, when this package is installed lokinet's systemd service is enabled by default as that is what normal users would expect to happen.
you can explicitly disable the lokinet service using from starting automatically on boot using `systemctl disable lokinet.service` or using a graphial ui for managing systemd units if provided by your linux distro.

**Comment by iHnR** [comment]
Thanks. I didn't know of systemctl gui yet. I would still suggest adding a toggle in the gui so it's more clear for the average user.
