### ISSUE TITLE
My ip is not hide by Lokinet

### ISSUE THREAD

**Issue by Arkim1er** [oxen-io/lokinet#2026]
Hello everydody,

After launching lokinet , i test my ip and i can see it

I'm under Ubuntu 22.04LTS on pc via wifi connection . My lokinet version is lokinet0.9.9deb

Someone else encounter the same problem ?

**Comment by majestrate** [comment]
exit node selection is manual and therefore off by default. 

we have a list maintained by the community of known exits here: http://probably.loki/wiki/index.php?title=Exit_Nodes 

this feature isnt done yet and the ux will change for the production level release for exits.

**Comment by Arkim1er** [comment]
@majestrate Thanks a lot and sorry for the disturbance

**Comment by majestrate** [comment]
yw, this is the next major feature
