### ISSUE TITLE
systemd resolved uses wrong source address

### ISSUE THREAD

**Issue by majestrate** [oxen-io/lokinet#2044]
debian bookworm's systemd resolved uses the lokitun0 ip for source address for dns queries

`23:54:25.327088 IP 172.16.0.1.55677 > 127.0.0.1.553: UDP, length 40`

version info:

```
resolvectl --version
systemd 251 (251.6-1)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

**Comment by majestrate** [comment]
this was captured from the lokitun0 interface

**Comment by majestrate** [comment]
possible solution:

default l3-intercept to on and bind dns to interface address except .0 not .1

**Comment by jagerman** [comment]
Cannot reproduce (using the exact same systemd version).

**Comment by majestrate** [comment]
applied holy water and it worked again.
