### ISSUE TITLE
Latest Lokinet version missing from oxen.rocks website

### ISSUE THREAD

**Issue by jahway603** [oxen-io/lokinet#2096]
Describe issue:

* Go to [oxen.rocks website](https://oxen.rocks/oxen-io/loki-network/)
* Search for "lokinet-linux-amd64" on the page
* See that the latest release there is https://oxen.rocks/oxen-io/loki-network/lokinet-linux-amd64-v0.9.9.tar.xz from May 2022

Will new releases not be released on the oxen.rocks website anymore? Should we just use the Github releases instead?

**Comment by jagerman** [comment]
I see the 0.9.10 and .11 builds there, but I missed them at first as well: they are sorted alphabetically and so are showing up between 0.9.1 and 0.9.2, rather than after 0.9.9.
