### ISSUE TITLE
Should not ping oxend before it has a key

### ISSUE THREAD

**Issue by jagerman** [oxen-io/lokinet#2125]
Currently on restart of oxend/lokinet on a service node I frequently see:
```
Jan 26 20:07:54 charolais oxend[3442125]: 2023-01-27 00:07:54.821	E Invalid Lokinet pubkey: expected 1f314f1273f14afd6f32bcb8bc7a4125faf253094f41fa2ecba4d8d588b5567a, received 0000000000000000000000000000000000000000000000000000000000000000
```
and then 30 seconds later a proper ping:
```
Jan 26 20:08:24 charolais oxend[3442125]: 2023-01-27 00:08:24.821	I Received ping from Lokinet 0.9.11
```
So it seems the first ping lokinet sends to oxend is sent *before* it has retrieved or properly set its pubkey.

We should not send the oxend ping if the pubkey has not yet been set.

**Comment by majestrate** [comment]
On Thu, 26 Jan 2023 16:11:15 -0800
Jason Rhinelander ***@***.***> wrote:

> Currently on restart of oxend/lokinet on a service node I frequently
> see: ```
> Jan 26 20:07:54 charolais oxend[3442125]: 2023-01-27
> 00:07:54.821	E Invalid Lokinet pubkey: expected
> 1f314f1273f14afd6f32bcb8bc7a4125faf253094f41fa2ecba4d8d588b5567a,
> received
> 0000000000000000000000000000000000000000000000000000000000000000 ```
> and then 30 seconds later a proper ping: ``` Jan 26 20:08:24
> charolais oxend[3442125]: 2023-01-27 00:08:24.821	I Received
> ping from Lokinet 0.9.11 ``` So it seems the first ping lokinet sends
> to oxend is sent *before* it has retrieved or properly set its pubkey.
> 
> We should not send the oxend ping if the pubkey has not yet been set.
> 

this should have an easy fix. we should include this and do a 0.9.12
tag.

-- 
~jeff
