### ISSUE TITLE
deb.oxen.io has no source packages for bullseye

### ISSUE THREAD

**Issue by majestrate** [oxen-io/lokinet#2135]
currently the apt repo on deb.oxen.io has no source packages for `lokinet` or `lokinet-bin`

`/etc/apt/sources.list.d/oxen.list` contains

``` 
deb https://deb.oxen.io bullseye main
deb-src https://deb.oxen.io bullseye main
```

and trying a `apt build-dep lokinet` gives me

```
# apt build-dep lokinet
Reading package lists... Done
E: Unable to find a source package for lokinet
```

**Comment by jagerman** [comment]
Not sure what happened there; I've re-pushed the repo; let me know if it still isn't working.

**Comment by majestrate** [comment]
still not up, not sure what is going on

**Comment by jagerman** [comment]
Oh, no *source* package, I missed that.

Going to close it as wontfix, at least for now; the source is entirely in the git repo (the `debian/bullseye` branch); it isn't worth the hassle of generating and uploading source packages.

**Comment by jagerman** [comment]
(Also: `mk-build-deps` is what you would use from within the `debian/bullseye` branch to install its declared build-deps, e.g.  `mk-build-deps -i -r debian/control`)
