### ISSUE TITLE
forwarding another port to lokinet

### ISSUE THREAD

**Issue by resession** [oxen-io/lokinet#2143]
in tor, we are able to make nginx listen on port 8080(or another port chosen by the user) and then we can forward that chosen port to port 80.
so in nginx port 8080 > tor port 80

it would be great if we can choose our own port. as of right now on lokinet, nginx has to listen on port 80 and we can not choose another port, so would it be great if this feature can be added
so it would look like this
nginx port 8080 > lokinet port 80

**Comment by majestrate** [comment]
this is the job of your os firewall. 
lokinet is an onion routed unicast ip tunnel and we have no reason to implement our own os firewall into it.

**Comment by majestrate** [comment]
keep in mind: "tor does it" is a reason to explicitly be skeptical of adding such functionality to lokinet.
