### ISSUE TITLE
remove libunbound in favor of getdns

### ISSUE THREAD

**Issue by majestrate** [oxen-io/lokinet#2156]
libunbound is a very annoying dependancy that is deeply irritating to use as it has a very under exposed api that ends up being too black box for what we are doing.

i want to replace all our usage of it with https://github.com/getdnsapi/getdns

**Comment by majestrate** [comment]
pros: 

* native libuv event loop support
* does not need libunbound if you are just using it as a stub resolver
* gnutls support
* DoT/DoH support baked in and is obvious how it works


cons:

* yet another todo item ( i need one con here ).

**Comment by jagerman** [comment]
Huge con: does not support DNS request caching.  We had that omission in lokinet once upon a time, and it was a miserable experience.

**Comment by jagerman** [comment]
One more: still requires libunbound for recursive queries, and doesn't support libunbound (and thus recursive queries) on windows.

**Comment by majestrate** [comment]
we dont do recursive queries we only act as a stub resolver right now.

i dont think lokinet should cache any dns that really is out of scope as we arent a dns resolver but more like a dns mitm filter to intercept queries for .loki and .snode

**Comment by majestrate** [comment]
we still would need to bundle a dns cache next to lokinet but it really shouldnt be inside lokinet imo.

**Comment by majestrate** [comment]
ideally i'd like to have lokinet not do any bare dns queries to upstream by default (or ever if we can help it). eventually i'd like to proxy dnscrypt traffic to a resolver via whatever .snode they happen to have paths to (having a sensible default upstream that users can override of course) but really we shouldn't be doing bare queries at all and libunbound doesn't have a very sane api for doing that. i also deeply despise libunbound as it has been the bane of my dev workflow making windows port work. i really just want it to be gone.

**Comment by majestrate** [comment]
we'll do this later maybe. not this year.
