### ISSUE TITLE
System level localhost proxy as an alternative to lokinet vpn

### ISSUE THREAD

**Issue by Destroyinator69420** [oxen-io/lokinet#2161]
I have had large amounts of problems using lokinet vpn on windows 11. Windows 11 supports system wide proxy settings. Lokinet could host a localhost http, https and socks5 proxy and use its admin rights to set the system proxy to the localhost http, https and socks5 proxies. I would also allow us to tunnel one specific app such as firefox without tunneling the entire system. It should not conflict with other localhost ports such as 8888, (freenet classic), 7657, 7070, or 7667 (i2p router console), 4444/4445 (i2p http proxy) or 9050/9150 (tor). It should check to make sure the port it will use is not occupied to make sure it does not disrupt anything else.

**Comment by majestrate** [comment]
On Fri, 21 Apr 2023 10:24:10 -0700
Destroyinator69420 ***@***.***> wrote:

> I have had large amounts of problems using lokinet vpn on windows 11.
> Windows 11 supports system wide proxy settings. Lokinet could host a
> localhost http, https and socks5 proxy and use its admin rights to
> set the system proxy to the localhost http, https and socks5 proxies.

use those other networks if you want to use things that way. it's
horrible and we will never add it to lokinet as we dont have to, you
can always just run a local proxy server and have it force upstream via
lokinet's tun interface.

this isn't the 1990s we can do selective routing. the correct approach
is to fix windows NOT to make lokinet MORE hacky and broken.

> I would also allow us to tunnel one specific app such as firefox
> without tunneling the entire system. It should not conflict with
> other localhost ports such as 8888, (freenet classic), 7657, 7070, or
> 7667 (i2p router console), 4444/4445 (i2p http proxy) or 9050/9150
> (tor). It should check to make sure the port it will use is not
> occupied to make sure it does not disrupt anything else.
> 


-- 
~jeff
