### ISSUE TITLE
DNS error

### ISSUE THREAD

**Issue by q116049762** [oxen-io/lokinet#2178]
When I opened it on Windows, there was a DNS error and I couldn't access the internet

**Comment by majestrate** [comment]
On Friday, 19 May 2023 02:40:44 EDT q116049762 wrote:
>  When I opened it on Windows, there was a DNS error and I couldn't access
> the internet


hi, 
thank you for the bug report. can you tell us the build number of windows, the 
version number of lokinet, which install options you gave lokinet when you 
installed it, if you are on a heavily filtered ISP and any additional 
information about how this bug got triggered.

-- 
~jeff
