### ISSUE TITLE
No `contrib/systemd-resolved/lokinet.conf` file.

### ISSUE THREAD

**Issue by tkr-sh** [oxen-io/lokinet#2184]
**Describe the bug**
Missing the file `contrib/systemd-resolved/lokinet.conf` mentioned here: https://github.com/oxen-io/oxen-docs/blob/master/docs/Lokinet/Guides/Install.md

A more detailed installation process for distro that don't use APT as a package manager will also help.

**Comment by jagerman** [comment]
See the readme and files in https://github.com/oxen-io/lokinet/tree/dev/contrib/systemd-resolved about what needs to be set up to allow lokinet to interact with systemd-resolved.
