### ISSUE TITLE
useradd: invalid flag for Pre-in RPM Scriptlet

### ISSUE THREAD

**Issue by ghost** [oxen-io/lokinet#2187]
**Describe the bug**
The Pre-In Scriptlet provided in Lokinet-0.9.8-1.x86_64.rpm on rpm.oxen.io/opensuse/tumbleweed has a typo for the useradd command flag `useradd --badnames`, should be `useradd --badname`

Results in installation failure due to missing user `_lokinet`

```
Retrieving: lokinet-0.9.8-1.x86_64 (Oxen Project)                   (2/2),  23.3 KiB
Retrieving: lokinet-0.9.8-1.x86_64.rpm ...........................................[done]
Checking for file conflicts: .....................................................[done]
useradd: unrecognized option '--badnames'
...
Options:
      --badname                 do not check for bad names
```

Immediate fix for Tumbleweed users: run `useradd --groups _loki _lokinet` before trying to install the package.

**Device and Operating system (please complete the following information):**
 - OS: OpenSUSE Tumbleweed 20230601 x86_64
-  Device: PC
 - Lokinet Version number or Git commit hash: 0.9.8

**Comment by majestrate** [comment]
fixed by https://github.com/oxen-io/lokinet/commit/f4c4b798ce3a4cf985d3edc487ddf635f78c0d6c
