### ISSUE TITLE
[discussion] lokinet vs lightning network onion routing

### ISSUE THREAD

**Issue by venezuela01** [oxen-io/lokinet#2188]
The Bitcoin lightning network protocol implements a builtin onion routing network:

https://github.com/lightning/bolts/blob/master/04-onion-routing.md

https://github.com/lightningnetwork/lightning-onion

It would be nice to research and compare Lokinet vs BTC lightning network onion routing.
Either we can borrow interesting ideas from them, or we can help them with ours.

**Comment by majestrate** [comment]
looks like they are doing per hop authenticated encryption in a similar way that i was thinking of doing it in lokinet, neat.

**Comment by majestrate** [comment]
can we move this to the discussions area along with #2190 ? thanks.
