### ISSUE TITLE
Nixos: Unable to use lokinet

### ISSUE THREAD

**Issue by 0xMRTT** [oxen-io/lokinet#2201]
**Describe the bug**
I tried to use lokinet on NixOS with the following config

```
services.lokinet = {
  enable = true;
  settings = {
    network.exit-node = [ "exit.loki" ];
  };
};
```

I've systemd-resolvd and lokinetrunning, but when i run this config, i don't have any internet access. In the logs, I see a lot of:

```
[path:warning|llarp/path/pathbuilder.cpp:354] endpoint:4erkkzakwxsabh8ocyy7xdj75gmf8rr78ni5f847fxgpgkiiuuxo.loki has no first hop candidate
[:warning|llarp/service/endpoint.cpp:118] could not publish descriptors for endpoint endpoint:4erkkzakwxsabh8ocyy7xdj75gmf8rr78ni5f847fxgpgkiiuuxo.loki because we couldn't get enough valid introductions
```

Is the issue with lokinet or with a misconfiguration on my end ?

**To Reproduce**
Use the previous config on Nixos

**Screenshots Or Logs**
See previously

**Device and Operating system (please complete the following information):**
 - OS: [e.g. iOS, Windows, Android] NixOS
-  Device: [ e.g. Mac, PC, IPhone] PC 
 - Lokinet Version number or Git commit hash: 0.9.11

**Comment by majestrate** [comment]
is there an issue with nixos's lokinet package too? this error line is reported when lokinet cannot connect to a first hop on the network, and a large number of things could cause this to occur.

**Comment by wyndon** [comment]
You need to use `useLocally` for it to modify the DNS settings automatically. I'm not so sure why we did this at the time, if you can think of a better way to handle this let me know, or open a PR on nixpkgs.

We can close as it's not related to this repo.
