### ISSUE TITLE
trojan dont download

### ISSUE THREAD

**Issue by DRAGON12367** [oxen-io/lokinet#2237]
**Describe the bug**

**To Reproduce**

**Screenshots Or Logs**
If applicable, add screenshots or log files to help explain your problem.

**Device and Operating system (please complete the following information):**
 - OS: [e.g. iOS, Windows, Android]
-  Device: [ e.g. Mac, PC, IPhone]
 - Lokinet Version number or Git commit hash:

**Comment by TommyTran732** [comment]
Where is the trojan?

**Comment by Ashthetik** [comment]
Hi @DRAGON12367 
No part of Lokinet, or any system of Oxen's, contains or serves malware. If your anti-virus is returning it as flagged, I'd recommend confirming that you have installed it from the official services and not third-party. There's also a chance that AVs like Windows Defender are falsely flagging Loki; in this case, I recommend replicating the install steps in a virtual machine and observing the outcome (if it is the same and is installed from Oxen's official sources, then there may be chance for reproduction if you could provide the system information and current Loki version/hash).

I'd like to add that I am in no way connected or representing Oxen.io, and all comments and thoughts are my own.

**Comment by jagerman** [comment]
I suppose, in a traditional literary sense, you could consider Lokinet a "trojan horse" in that it tunnels your network traffic through a barrier to get to another place, undetected and unimpeded.

As for the malicious computer program sense, it is not.  As @Ashthetik pointed out, if it's being falsely flagged as such, that is just indicating that your virus scanner is malfunctioning; if you provide some information on what AV program you're using, we might be able to submit a report to them to have them stop falsely flagging lokinet.  (Though in the past this hasn't been particularly effective: the less reputable AV companies are in the business of getting you to keep paying by scaring you and thus actually *want* false positives to keep you scares and paying).

But at the moment, as you have provided no information at all other than a scare issue subject, I'm closing this issue.

**Comment by DRAGON12367** [comment]
virustotal
    On Wednesday, May 22, 2024 at 02:32:01 p.m. EDT, Jason Rhinelander ***@***.***> wrote:  
 
 


I suppose, in a traditional literary sense, you could consider Lokinet a "trojan horse" in that it tunnels your network traffic through a barrier to get to another place, undetected and unimpeded.

As for the malicious computer program sense, it is not. As @Ashthetik pointed out, if it's being falsely flagged as such, that is just indicating that your virus scanner is malfunctioning; if you provide some information on what AV program you're using, we might be able to submit a report to them to have them stop falsely flagging lokinet. (Though in the past this hasn't been particularly effective: the less reputable AV companies are in the business of getting you to keep paying by scaring you and thus actually want false positives to keep you scares and paying).

But at the moment, as you have provided no information at all other than a scare issue subject, I'm closing this issue.
