### ISSUE TITLE
reopen #2245

### ISSUE THREAD

**Issue by nanderer** [oxen-io/lokinet#2246]
please reopen #2245 . it was closed without understanding the main intend. thx

**Comment by jagerman** [comment]
Please stop abusing the issue tracker.

**Comment by nanderer** [comment]
imho i am not abusing anythin @jagerman ; please state your reason for acting so different then what you did 7h ago, i mean there you adopted my suggestions and tagt the issue apropably and now you just drop it for no reason??? i dont get it!

**Comment by nanderer** [comment]
@jagerman thanks for adding this comment, that makes it clear
