### ISSUE TITLE
add [ip address].loki resolving to dns for mapping ips to go over exit using private range

### ISSUE THREAD

**Issue by majestrate** [oxen-io/lokinet#227]

**Comment by liilac** [comment]
Can you elaborate on this?

What's the use case, as opposed to just using normal routing?

Also, to be clear, do you mean public internet IPv4 addresses?  IPv6 support intended as well?

**Comment by majestrate** [comment]
it's so we don't need to do SO_BINDTODEVICE we resolve something like `1.2.3.4.in-addr` which maps to a private range that we own. it was for lokid
