### ISSUE TITLE
Vanity Hidden Service Address generator

### ISSUE THREAD

**Issue by neuroscr** [oxen-io/lokinet#60]
Tickle the nonce until you get the prefix you've always want

**Comment by liilac** [comment]
To document some of the discussion on this,  hashcat support for this has been considered, for which I would be the likely developer and maintainer.

Hashcat support is ideal from the perspective of encouraging security testing / penetration testing, however my assessment so far is that it's not likely to be ideal for vanity address generation as the concept of generating a private key whose fingerprint fits a certain pattern doesn't fit neatly into the hashcat model.  That said, I would like to explore this further.

My thoughts were to write this as a standalone Go program with OpenCL kernels for the actual crypto operations.  

I would strongly consider writing and maintaining a Metal variant of this, especially targeting mobile devices, as it may (minorly) encourage adoption for there to be hardware accelerated mobile apps for this sort of thing.  It'd also be interesting to demonstrate the relative capacity of mobile hardware for bulk crypto, especially in a context that is highly similar to private key/hash cracking.

**Comment by neuroscr** [comment]
We have a (SLOW) reference implementation now in python
https://github.com/loki-project/loki-network/tree/master/contrib/py/vanity

**Comment by liilac** [comment]
Landed up forgetting about this in favour of other priorities.

I wrote two much faster implementations around the time of this discussion, will see about uploading those later.  One uses accelerated CPU instructions, works and is finished, the other was an OpenCL one I didn't get around to finishing.

**Comment by majestrate** [comment]
On Tue, Apr 16, 2019 at 12:52:00AM -0700, Lilac wrote:
> Landed up forgetting about this in favour of other priorities.
> 
> I wrote two much faster implementations around the time of this discussion, will see about uploading those later.  One uses accelerated CPU instructions, works and is finished, the other was an OpenCL one I didn't get around to finishing.
We had to change our public signing key format to match loki/monero so it's now using a non libsodium key format. just a heads up.

**Comment by liilac** [comment]
Oh, well then I would probably need to update those.  They were written in December 2018.
