### ISSUE TITLE
Network Level PoW?

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/lokinet#612]
Popular Hidden services on Tor often experience DoS and DDoS attacks, unlike traditional web services, hidden services cannot deploy intermediate services like Cloudflare which can check browser fingerprints (Tor browser prevents this) and IP address reputation. Tor Hidden services also lack the ability to block spammers via IP addresses since Tor cannot reveal the IP address of the person requesting the content. 

The common approach to deal with such DoS attempts usually involves load balancing (Onion balance) or  serving a CAPTCHA that users must complete. Neither of which provide very effective protection.

Adding protection at the Application layer with a CAPTCHA adds a new vector for spammers, adding protections at higher layers for Lokinet would require each SNApp operator to run additional software rather than being easily fixed inside Lokinet.

Although Lokinet operates many layers below Tor browser and a single layer below Tor itself i think it would still be a good idea to look at adding protection against DoS and DDoS attacks at the network layer. 

What im proposing is that any SNApp operator should be able to enable a setting called SNApp PoW in lokinet.ini (By default it would be turned off).

“SNApp PoW = True”
“SNApp PoW = Hard” (Allows the user to tune the difficulty of such a PoW)

If SNApp PoW is turned on then any introduction sets that the SNApp now publishes should require the introducer and the endpoint to verify the specified amount of PoW. 

This means that before the attacker can establish a connection to the SNApp he must have a valid PoW, which is checked by the introducer before they handout the endpoints for a SNApp and by the endpoints themselves.

**Comment by majestrate** [comment]
On Mon, May 20, 2019 at 08:03:40PM -0700, Kee Jefferys wrote:
> Popular Hidden services on Tor often experience DoS and DDoS attacks, unlike traditional web services, hidden services cannot deploy intermediate services like Cloudflare which can check browser fingerprints (Tor browser prevents this) and IP address reputation. Tor Hidden services also lack the ability to block spammers via IP addresses since Tor cannot reveal the IP address of the person requesting the content. 
> 
> The common approach to deal with such DoS attempts usually involves load balancing (Onion balance) or  serving a CAPTCHA that users must complete. Neither of which provide very effective protection.
> 
> Adding protection at the Application layer with a CAPTCHA adds a new vector for spammers, adding protections at higher layers for Lokinet would require each SNApp operator to run additional software rather than being easily fixed inside Lokinet.
> 
> Although Lokinet operates many layers below Tor browser and a single layer below Tor itself i think it would still be a good idea to look at adding protection against DoS and DDoS attacks at the network layer. 
> 
> What im proposing is that any SNApp operator should be able to enable a setting called SNApp PoW in lokinet.ini (By default it would be turned off).
> 
> “SNApp PoW = True”
> “SNApp PoW = Hard” (Allows the user to tune the difficulty of such a PoW)
> 
> If SNApp PoW is turned on then any introduction sets that the SNApp now publishes should require the introducer and the endpoint to verify the specified amount of PoW. 

it should probably be tunable as an integer number of prefixed 0 bits generated by the PoW hash. "hard" and "true" don't really convey anything useful.

**Comment by michael-loki** [comment]
Agreed. A numerical value which expresses *something* is probably the right thing to use. 

How you express work (and proof) as a single number might be tricky (no. blocks?)

**Comment by neuroscr** [comment]
The reason previously discussion why not an integer was meta-data leakage. A specific integer could be used to identify paths for a specific hidden service. So by have predefined levels, traffic is less likely to be identified.

**Comment by majestrate** [comment]
> The reason previously discussion why not an integer was meta-data leakage. 
what leaks where?
> A specific integer could be used to identify paths for a specific hidden service. So by have predefined levels, traffic is less likely to be identified.

it depends on where the PoW is added.

**Comment by neuroscr** [comment]
Jeff said today, wrong way to address path building flooding
