### ISSUE TITLE
Wintun for windows

### ISSUE THREAD

**Issue by rjmalagon** [oxen-io/lokinet#710]
This is more an enhancement suggestion than a bug squash request.
The OpenVpn tun driver for windows feels like somewhat dirty. The loki-network node clash with my custom CJDNS node OpenVpn tun interface for Windows.
I don't feel that this a bug in loki-network tun code, but I feel sorry that I can't code Wintun tun code for loki-nework (and for CJDNS too).
Wintun is much a beta code and fast evolving but feels right. https://www.wintun.net/

WARNING WARNING - onion routing fan cheers below -
I am a longtime TOR and I2P user and now I am a happy loki-network tester and (small) bandwidth contributor, thanks to the developers for this very interesting project.

**Comment by despair86** [comment]
o hi

i'm the lokinet guy working on Windows NT

yes I've been looking into using `wintun` lately, but isn't wireguard itself still somewhat unstable? i'd imagine this would too.

in any case, a big switch isn't in the cards yet until i can patch in some NDIS 5.x bits into it (yes Loki has an EV cert for 64-bit driver stuff)

**Comment by rjmalagon** [comment]
Hi, nice to read you.
Jason A. Donenfeld is such a perfectionist, he sees unstable code where I see cleaner code than the alternatives (or my love/hate relationship with CJDNS). 
I think is a good idea to check on wintun later when the code is near a freeze stage.

Kudos, winnt device driver programmer is a serious thing.

For fun read, some openvpn experiments with wintun are in place
https://patchwork.openvpn.net/patch/772/

**Comment by majestrate** [comment]
i think that wintun is a good idea i've heard the perf is better vs tun/tap driver
