### ISSUE TITLE
change default upstream dns to not cloudflare

### ISSUE THREAD

**Issue by majestrate** [oxen-io/lokinet#765]
right now we default to cloudfare dns as upstream we could do the following:

* have debian lokinet package require dnscrypt-proxy for upstream dns
* have some kind of resolvconf hook that uses the old contents of `resolv.conf` to generate upstream dns settings
* don't have default upstream dns (this is dangerous as it will make slow queries leak)

**Comment by jagerman** [comment]
Don't *all* of the above leak slow queries currently?

**Comment by majestrate** [comment]
>Don't all of the above (and the current cloudflare default) leak slow queries currently?
no because all hooked lookups don't get forwarded by the lokinet resolver it eats them, given you have configured dns correctly (lokinet is your only resolver) it will not leak.

**Comment by jagerman** [comment]
Oh, right.

In this case I much prefer option 2; it's the only one that doesn't break local network DNS resolution and keeps your latency lower for most services by continuing to use the local network DNS caching that pretty much all routers do.

**Comment by neuroscr** [comment]
what about DNS over HTTPS? would that be easier to implement cross-platform in our architecture?

**Comment by majestrate** [comment]
dns over https is out of scope

**Comment by majestrate** [comment]
in addition for DNS over HTTPS to work we would need to pull in

* ASN.1
* X509
* CA cert root trusts


it is absolutely not easier by any measure

**Comment by neuroscr** [comment]
we already have to bring an https client for bootstrap downloading

**Comment by despair86** [comment]
upstream DNS: is quad9 any better

**Comment by Chief36** [comment]
Can the default upstream DNS be set as a the system-wide DNS set by systemd-resolvd or the ones specified in resolv.conf ?

**Comment by Pantyhose-X** [comment]
I recommend changing the default upstream dns using （Protocol: DNSCrypt | Features: Non-logging, Non-filtering, DNSSEC ) from [dnscrypt](https://dnscrypt.info/)

Chinese government blocks [DNS-over-TLS  DNS-over-QUIC  DNS-over-HTTPS](https://geneva.cs.umd.edu/posts/)

**Comment by majestrate** [comment]
> I recommend changing the default upstream dns using （Protocol: DNSCrypt | Features: Non-logging, Non-filtering, DNSSEC ) from [dnscrypt](https://dnscrypt.info/)
> 
> Chinese government blocks [DNS-over-TLS DNS-over-QUIC DNS-over-HTTPS](https://geneva.cs.umd.edu/posts/)

see https://github.com/oxen-io/lokinet/issues/1704

**Comment by majestrate** [comment]
this issue has been fixed by using quad nine.
