### ISSUE TITLE
Lokinet cannot open /dev/net/tun in NixOS

### ISSUE THREAD

**Issue by Chiiruno** [oxen-io/lokinet#868]
**Describe the bug**
Lokinet attempts to open `/dev/net/tun`, and it cannot, I'm not entirely sure if it's a libcap issue with the service, but it does work when ran as root.
See below screenshots of logs in the VM used to test for more info.
Also see https://github.com/NixOS/nixpkgs/pull/69175/files.

**To Reproduce**
Use NixOS, or the nix package manager, clone the nixpkgs repo, apply https://github.com/NixOS/nixpkgs/pull/69175, run service as vm test https://nixos.wiki/wiki/Cheatsheet#Building_a_service_as_a_VM_.28for_testing.29.

**Screenshots Or Logs**
![Screenshot_20191016_193940](https://user-images.githubusercontent.com/30435868/66969023-70f89c80-f04d-11e9-9acd-34b548f97cfd.png)
![Screenshot_20191016_193956](https://user-images.githubusercontent.com/30435868/66969024-71913300-f04d-11e9-967a-2089172eed45.png)
![Screenshot_20191016_194001](https://user-images.githubusercontent.com/30435868/66969025-71913300-f04d-11e9-9a31-fcfce6f6ec31.png)
![Screenshot_20191016_194047](https://user-images.githubusercontent.com/30435868/66969026-71913300-f04d-11e9-94ed-1b63b762621f.png)

**Device and Operating system (please complete the following information):**
 - OS: Linux (NixOS)
-  Device: PC
 - Lokinet Version number or Git commit hash: 0.5.2
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.6, NixOS, 19.09.789.7952807791d (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixos-19.09.809.5000b1478a1, nixos-unstable-20.03pre196725.94500c93dc2"`
 - channels(okina): `"nixos-19.09.809.5000b1478a1, nixos-unstable-20.03pre196725.94500c93dc2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by majestrate** [comment]
is the lokinet binary setcap'd correctly?

**Comment by Chiiruno** [comment]
The binary itself, I had to disallow that in the setup, but the systemd service should take care of that: https://github.com/NixOS/nixpkgs/pull/69175/files#diff-e0f3ba075eda0a25e0e6bb1e8cfd038bR214

**Comment by majestrate** [comment]
i am unfamiliar with systemd's caps features but it seems that it should be something like this:

    AmbientCapabilities = [ "cap_net_admin" "cap_net_bind_service" ];

without the trailing `+eip`

**Comment by Chiiruno** [comment]
Already tried that, but I tried again just in case, and yeah, no dice, still exact same error(s).

**Comment by majestrate** [comment]
try adding

`SecureBits=keep-caps` 

option to systemd unit, looks like the `i` in `setcap +eip` means that the process can inherit caps which is not the default case in systemd caps.

**Comment by majestrate** [comment]
actually that *is* the default too...

... what if you make the capabilities all uppercase? (surely that won't fix it but wouldn't it be funny if it did)

**Comment by majestrate** [comment]
you are also using `DynamicUser` which doesn't allow write access to anything in `/dev` so maybe adding a `ReadWritePaths=/dev/net/tun` would help?

**Comment by Chiiruno** [comment]
>you are also using DynamicUser which doesn't allow write access to anything in /dev so maybe adding a ReadWritePaths=/dev/net/tun would help?

I bet that's the problem, thank you so much. Will test.

**Comment by Chiiruno** [comment]
I suppose I was a bit premature.
Tried a lot of variations of
```
SecureBits = "keep-caps";
ReadWritePaths = "/dev/net/tun";
AmbientCapabilities = [ "cap_net_admin" "cap_net_bind_service+eip" ];
```

`SecureBits` seems to throw some errors when used with any variation of "=+eip", etc.

**Comment by majestrate** [comment]
remove the `+eip` maybe?

**Comment by Chiiruno** [comment]
Yeah, I've tried that, and of course I've omitted some of the above lines too when testing.

**Comment by Chiiruno** [comment]
Does lokinet spawn a new process when fiddling with `/dev/net/tun`?

**Comment by majestrate** [comment]
>Does lokinet spawn a new process when fiddling with /dev/net/tun?
yes, everything is done in another thread so that main thread can process stuff and clean up unconditionally. we can probably change that if needed.

**Comment by Chiiruno** [comment]
I'm thinking it might be some sort of inheritance security thing, with `SecureBits` not allowing `keep-on` with any variation of `eip`.

**Comment by majestrate** [comment]
what about just:

```
ReadWritePaths = "/dev/net/tun";
AmbientCapabilities = [ "cap_net_admin" "cap_net_bind_service" ];
```
what error does it yield with that?

**Comment by Chiiruno** [comment]
Same as the OP, can't open `/dev/net/tun`.

**Comment by majestrate** [comment]
what about adding:

```
NoNewPrivileges=false
```

it seems that systemd turns that on when you use `DynamicUser`

**Comment by majestrate** [comment]
it seems like using `DynamicUser` forces `NoNewPrivileges=true` and it cannot be overriden.

**Comment by Chiiruno** [comment]
Seems to be the case, I've been testing with several variations with `NoNewPrivileges` and still no dice.

**Comment by Chiiruno** [comment]
How much of lokinet actually needs these privileges?
Would it be possible to have another executable that could run as root and have the rest be unprivileged?

**Comment by majestrate** [comment]
>How much of lokinet actually needs these privileges?

setting up the network interfaces and dns sockets need those.

> Would it be possible to have another executable that could run as root and have the rest be unprivileged?

that is the direction we want to go in going forward for many other reasons. i'll bump up its priority.

**Comment by majestrate** [comment]
i think that we do hard depend on being able to use `/dev/net/tun`

**Comment by wyndon** [comment]
Can be closed as we're now able to access /dev/net/tun even as non-root user. (https://github.com/NixOS/nixpkgs/pull/175335)

**Comment by majestrate** [comment]
we are going to tag 0.9.9 tommorrow. you may want to use that one.

**Comment by majestrate** [comment]
fun fact, this new tag adds exit node pooling using multiple `exit-node=` entries in which it will randomly allocate an exit given a cidr (currently /32 , hope to expose it via config tunable in 0.9.10)

**Comment by wyndon** [comment]
> fun fact, this new tag adds exit node pooling using multiple `exit-node=` entries in which it will randomly allocate an exit given a cidr (currently /32 , hope to expose it via config tunable in 0.9.10)

Thanks for the info. Will add support for that
